// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="comDescriptor_accel,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.537000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=58,HLS_SYN_DSP=4,HLS_SYN_FF=639789,HLS_SYN_LUT=196047,HLS_VERSION=2018_3}" *)

module comDescriptor_accel (
        ap_clk,
        ap_rst_n,
        srcStream_V_V_TDATA,
        srcStream_V_V_TVALID,
        srcStream_V_V_TREADY,
        dataStreamIn_V_V_TDATA,
        dataStreamIn_V_V_TVALID,
        dataStreamIn_V_V_TREADY,
        descriptor_out_TDATA,
        descriptor_out_TVALID,
        descriptor_out_TREADY,
        descriptor_out_TKEEP,
        descriptor_out_TSTRB,
        descriptor_out_TUSER,
        descriptor_out_TLAST,
        descriptor_out_TID,
        descriptor_out_TDEST
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst_n;
input  [7:0] srcStream_V_V_TDATA;
input   srcStream_V_V_TVALID;
output   srcStream_V_V_TREADY;
input  [87:0] dataStreamIn_V_V_TDATA;
input   dataStreamIn_V_V_TVALID;
output   dataStreamIn_V_V_TREADY;
output  [31:0] descriptor_out_TDATA;
output   descriptor_out_TVALID;
input   descriptor_out_TREADY;
output  [3:0] descriptor_out_TKEEP;
output  [3:0] descriptor_out_TSTRB;
output  [0:0] descriptor_out_TUSER;
output  [0:0] descriptor_out_TLAST;
output  [0:0] descriptor_out_TID;
output  [0:0] descriptor_out_TDEST;

 reg    ap_rst_n_inv;
reg   [7:0] srcStream_V_V_0_data_out;
wire    srcStream_V_V_0_vld_in;
wire    srcStream_V_V_0_vld_out;
wire    srcStream_V_V_0_ack_in;
reg    srcStream_V_V_0_ack_out;
reg   [7:0] srcStream_V_V_0_payload_A;
reg   [7:0] srcStream_V_V_0_payload_B;
reg    srcStream_V_V_0_sel_rd;
reg    srcStream_V_V_0_sel_wr;
wire    srcStream_V_V_0_sel;
wire    srcStream_V_V_0_load_A;
wire    srcStream_V_V_0_load_B;
reg   [1:0] srcStream_V_V_0_state;
wire    srcStream_V_V_0_state_cmp_full;
reg   [87:0] dataStreamIn_V_V_0_data_out;
wire    dataStreamIn_V_V_0_vld_in;
wire    dataStreamIn_V_V_0_vld_out;
wire    dataStreamIn_V_V_0_ack_in;
reg    dataStreamIn_V_V_0_ack_out;
reg   [87:0] dataStreamIn_V_V_0_payload_A;
reg   [87:0] dataStreamIn_V_V_0_payload_B;
reg    dataStreamIn_V_V_0_sel_rd;
reg    dataStreamIn_V_V_0_sel_wr;
wire    dataStreamIn_V_V_0_sel;
wire    dataStreamIn_V_V_0_load_A;
wire    dataStreamIn_V_V_0_load_B;
reg   [1:0] dataStreamIn_V_V_0_state;
wire    dataStreamIn_V_V_0_state_cmp_full;
reg   [31:0] descriptor_out_V_data_V_1_data_out;
wire    descriptor_out_V_data_V_1_vld_in;
wire    descriptor_out_V_data_V_1_vld_out;
wire    descriptor_out_V_data_V_1_ack_in;
wire    descriptor_out_V_data_V_1_ack_out;
reg   [31:0] descriptor_out_V_data_V_1_payload_A;
reg   [31:0] descriptor_out_V_data_V_1_payload_B;
reg    descriptor_out_V_data_V_1_sel_rd;
reg    descriptor_out_V_data_V_1_sel_wr;
wire    descriptor_out_V_data_V_1_sel;
wire    descriptor_out_V_data_V_1_load_A;
wire    descriptor_out_V_data_V_1_load_B;
reg   [1:0] descriptor_out_V_data_V_1_state;
wire    descriptor_out_V_data_V_1_state_cmp_full;
reg   [3:0] descriptor_out_V_keep_V_1_data_out;
wire    descriptor_out_V_keep_V_1_vld_in;
wire    descriptor_out_V_keep_V_1_vld_out;
wire    descriptor_out_V_keep_V_1_ack_in;
wire    descriptor_out_V_keep_V_1_ack_out;
reg   [3:0] descriptor_out_V_keep_V_1_payload_A;
reg   [3:0] descriptor_out_V_keep_V_1_payload_B;
reg    descriptor_out_V_keep_V_1_sel_rd;
reg    descriptor_out_V_keep_V_1_sel_wr;
wire    descriptor_out_V_keep_V_1_sel;
wire    descriptor_out_V_keep_V_1_load_A;
wire    descriptor_out_V_keep_V_1_load_B;
reg   [1:0] descriptor_out_V_keep_V_1_state;
wire    descriptor_out_V_keep_V_1_state_cmp_full;
reg   [3:0] descriptor_out_V_strb_V_1_data_out;
wire    descriptor_out_V_strb_V_1_vld_in;
wire    descriptor_out_V_strb_V_1_vld_out;
wire    descriptor_out_V_strb_V_1_ack_in;
wire    descriptor_out_V_strb_V_1_ack_out;
reg   [3:0] descriptor_out_V_strb_V_1_payload_A;
reg   [3:0] descriptor_out_V_strb_V_1_payload_B;
reg    descriptor_out_V_strb_V_1_sel_rd;
reg    descriptor_out_V_strb_V_1_sel_wr;
wire    descriptor_out_V_strb_V_1_sel;
wire    descriptor_out_V_strb_V_1_load_A;
wire    descriptor_out_V_strb_V_1_load_B;
reg   [1:0] descriptor_out_V_strb_V_1_state;
wire    descriptor_out_V_strb_V_1_state_cmp_full;
reg   [0:0] descriptor_out_V_user_V_1_data_out;
wire    descriptor_out_V_user_V_1_vld_in;
wire    descriptor_out_V_user_V_1_vld_out;
wire    descriptor_out_V_user_V_1_ack_in;
wire    descriptor_out_V_user_V_1_ack_out;
reg   [0:0] descriptor_out_V_user_V_1_payload_A;
reg   [0:0] descriptor_out_V_user_V_1_payload_B;
reg    descriptor_out_V_user_V_1_sel_rd;
reg    descriptor_out_V_user_V_1_sel_wr;
wire    descriptor_out_V_user_V_1_sel;
wire    descriptor_out_V_user_V_1_load_A;
wire    descriptor_out_V_user_V_1_load_B;
reg   [1:0] descriptor_out_V_user_V_1_state;
wire    descriptor_out_V_user_V_1_state_cmp_full;
reg   [0:0] descriptor_out_V_last_V_1_data_out;
wire    descriptor_out_V_last_V_1_vld_in;
wire    descriptor_out_V_last_V_1_vld_out;
wire    descriptor_out_V_last_V_1_ack_in;
wire    descriptor_out_V_last_V_1_ack_out;
reg   [0:0] descriptor_out_V_last_V_1_payload_A;
reg   [0:0] descriptor_out_V_last_V_1_payload_B;
reg    descriptor_out_V_last_V_1_sel_rd;
reg    descriptor_out_V_last_V_1_sel_wr;
wire    descriptor_out_V_last_V_1_sel;
wire    descriptor_out_V_last_V_1_load_A;
wire    descriptor_out_V_last_V_1_load_B;
reg   [1:0] descriptor_out_V_last_V_1_state;
wire    descriptor_out_V_last_V_1_state_cmp_full;
reg   [0:0] descriptor_out_V_id_V_1_data_out;
wire    descriptor_out_V_id_V_1_vld_in;
wire    descriptor_out_V_id_V_1_vld_out;
wire    descriptor_out_V_id_V_1_ack_in;
wire    descriptor_out_V_id_V_1_ack_out;
reg   [0:0] descriptor_out_V_id_V_1_payload_A;
reg   [0:0] descriptor_out_V_id_V_1_payload_B;
reg    descriptor_out_V_id_V_1_sel_rd;
reg    descriptor_out_V_id_V_1_sel_wr;
wire    descriptor_out_V_id_V_1_sel;
wire    descriptor_out_V_id_V_1_load_A;
wire    descriptor_out_V_id_V_1_load_B;
reg   [1:0] descriptor_out_V_id_V_1_state;
wire    descriptor_out_V_id_V_1_state_cmp_full;
reg   [0:0] descriptor_out_V_dest_V_1_data_out;
wire    descriptor_out_V_dest_V_1_vld_in;
wire    descriptor_out_V_dest_V_1_vld_out;
wire    descriptor_out_V_dest_V_1_ack_in;
wire    descriptor_out_V_dest_V_1_ack_out;
reg   [0:0] descriptor_out_V_dest_V_1_payload_A;
reg   [0:0] descriptor_out_V_dest_V_1_payload_B;
reg    descriptor_out_V_dest_V_1_sel_rd;
reg    descriptor_out_V_dest_V_1_sel_wr;
wire    descriptor_out_V_dest_V_1_sel;
wire    descriptor_out_V_dest_V_1_load_A;
wire    descriptor_out_V_dest_V_1_load_B;
reg   [1:0] descriptor_out_V_dest_V_1_state;
wire    descriptor_out_V_dest_V_1_state_cmp_full;
wire   [1:0] p_image_height_address0;
reg    p_image_height_ce0;
wire   [8:0] p_image_height_q0;
wire   [1:0] p_image_width_address0;
reg    p_image_width_ce0;
wire   [9:0] p_image_width_q0;
reg    srcStream_V_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    dataStreamIn_V_V_TDATA_blk_n;
reg    ap_block_state1;
reg   [8:0] p_image_height_load_reg_178;
wire    ap_CS_fsm_state2;
reg   [9:0] p_image_width_load_reg_183;
wire   [10:0] extLd_cast_fu_160_p1;
reg   [10:0] extLd_cast_reg_188;
wire    ap_CS_fsm_state3;
wire   [11:0] extLd1_cast_fu_164_p1;
reg   [11:0] extLd1_cast_reg_193;
wire   [31:0] grp_windowSlider_fu_112_descriptor_out_TDATA;
wire   [3:0] grp_windowSlider_fu_112_descriptor_out_TKEEP;
wire   [3:0] grp_windowSlider_fu_112_descriptor_out_TSTRB;
wire   [0:0] grp_windowSlider_fu_112_descriptor_out_TUSER;
wire   [0:0] grp_windowSlider_fu_112_descriptor_out_TLAST;
wire   [0:0] grp_windowSlider_fu_112_descriptor_out_TID;
wire   [0:0] grp_windowSlider_fu_112_descriptor_out_TDEST;
wire    grp_windowSlider_fu_112_src_V_V_TVALID;
wire    grp_windowSlider_fu_112_src_V_V_TREADY;
wire    grp_windowSlider_fu_112_dataPackStreamIn_V_V_TVALID;
wire    grp_windowSlider_fu_112_dataPackStreamIn_V_V_TREADY;
wire    grp_windowSlider_fu_112_ap_start;
wire    grp_windowSlider_fu_112_descriptor_out_TVALID;
wire    grp_windowSlider_fu_112_descriptor_out_TREADY;
wire    grp_windowSlider_fu_112_ap_done;
wire    grp_windowSlider_fu_112_ap_ready;
wire    grp_windowSlider_fu_112_ap_idle;
reg    grp_windowSlider_fu_112_ap_continue;
reg    grp_windowSlider_fu_112_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_sync_grp_windowSlider_fu_112_ap_ready;
wire    ap_sync_grp_windowSlider_fu_112_ap_done;
reg    ap_block_state4_on_subcall_done;
reg    ap_sync_reg_grp_windowSlider_fu_112_ap_ready;
reg    ap_sync_reg_grp_windowSlider_fu_112_ap_done;
wire   [63:0] tmp_fu_154_p1;
reg   [4:0] ap_NS_fsm;
wire    ap_CS_fsm_state5;
reg    ap_block_state5;

// power-on initialization
initial begin
#0 srcStream_V_V_0_sel_rd = 1'b0;
#0 srcStream_V_V_0_sel_wr = 1'b0;
#0 srcStream_V_V_0_state = 2'd0;
#0 dataStreamIn_V_V_0_sel_rd = 1'b0;
#0 dataStreamIn_V_V_0_sel_wr = 1'b0;
#0 dataStreamIn_V_V_0_state = 2'd0;
#0 descriptor_out_V_data_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_data_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_data_V_1_state = 2'd0;
#0 descriptor_out_V_keep_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_keep_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_keep_V_1_state = 2'd0;
#0 descriptor_out_V_strb_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_strb_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_strb_V_1_state = 2'd0;
#0 descriptor_out_V_user_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_user_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_user_V_1_state = 2'd0;
#0 descriptor_out_V_last_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_last_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_last_V_1_state = 2'd0;
#0 descriptor_out_V_id_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_id_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_id_V_1_state = 2'd0;
#0 descriptor_out_V_dest_V_1_sel_rd = 1'b0;
#0 descriptor_out_V_dest_V_1_sel_wr = 1'b0;
#0 descriptor_out_V_dest_V_1_state = 2'd0;
#0 ap_CS_fsm = 5'd1;
#0 grp_windowSlider_fu_112_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_windowSlider_fu_112_ap_ready = 1'b0;
#0 ap_sync_reg_grp_windowSlider_fu_112_ap_done = 1'b0;
end

comDescriptor_accWhU #(
    .DataWidth( 9 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_image_height_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(p_image_height_address0),
    .ce0(p_image_height_ce0),
    .q0(p_image_height_q0)
);

comDescriptor_accXh4 #(
    .DataWidth( 10 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
p_image_width_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(p_image_width_address0),
    .ce0(p_image_width_ce0),
    .q0(p_image_width_q0)
);

windowSlider grp_windowSlider_fu_112(
    .src_V_V_TDATA(srcStream_V_V_0_data_out),
    .dataPackStreamIn_V_V_TDATA(dataStreamIn_V_V_0_data_out),
    .descriptor_out_TDATA(grp_windowSlider_fu_112_descriptor_out_TDATA),
    .descriptor_out_TKEEP(grp_windowSlider_fu_112_descriptor_out_TKEEP),
    .descriptor_out_TSTRB(grp_windowSlider_fu_112_descriptor_out_TSTRB),
    .descriptor_out_TUSER(grp_windowSlider_fu_112_descriptor_out_TUSER),
    .descriptor_out_TLAST(grp_windowSlider_fu_112_descriptor_out_TLAST),
    .descriptor_out_TID(grp_windowSlider_fu_112_descriptor_out_TID),
    .descriptor_out_TDEST(grp_windowSlider_fu_112_descriptor_out_TDEST),
    .p_image_height(extLd_cast_reg_188),
    .p_image_width(extLd1_cast_reg_193),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .src_V_V_TVALID(grp_windowSlider_fu_112_src_V_V_TVALID),
    .src_V_V_TREADY(grp_windowSlider_fu_112_src_V_V_TREADY),
    .dataPackStreamIn_V_V_TVALID(grp_windowSlider_fu_112_dataPackStreamIn_V_V_TVALID),
    .dataPackStreamIn_V_V_TREADY(grp_windowSlider_fu_112_dataPackStreamIn_V_V_TREADY),
    .p_image_height_ap_vld(1'b1),
    .p_image_width_ap_vld(1'b1),
    .ap_start(grp_windowSlider_fu_112_ap_start),
    .descriptor_out_TVALID(grp_windowSlider_fu_112_descriptor_out_TVALID),
    .descriptor_out_TREADY(grp_windowSlider_fu_112_descriptor_out_TREADY),
    .ap_done(grp_windowSlider_fu_112_ap_done),
    .ap_ready(grp_windowSlider_fu_112_ap_ready),
    .ap_idle(grp_windowSlider_fu_112_ap_idle),
    .ap_continue(grp_windowSlider_fu_112_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_windowSlider_fu_112_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_windowSlider_fu_112_ap_done <= 1'b0;
        end else if ((grp_windowSlider_fu_112_ap_done == 1'b1)) begin
            ap_sync_reg_grp_windowSlider_fu_112_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_windowSlider_fu_112_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_windowSlider_fu_112_ap_ready <= 1'b0;
        end else if ((grp_windowSlider_fu_112_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_windowSlider_fu_112_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dataStreamIn_V_V_0_sel_rd <= 1'b0;
    end else begin
        if (((dataStreamIn_V_V_0_ack_out == 1'b1) & (dataStreamIn_V_V_0_vld_out == 1'b1))) begin
            dataStreamIn_V_V_0_sel_rd <= ~dataStreamIn_V_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dataStreamIn_V_V_0_sel_wr <= 1'b0;
    end else begin
        if (((dataStreamIn_V_V_0_ack_in == 1'b1) & (dataStreamIn_V_V_0_vld_in == 1'b1))) begin
            dataStreamIn_V_V_0_sel_wr <= ~dataStreamIn_V_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dataStreamIn_V_V_0_state <= 2'd0;
    end else begin
        if ((((dataStreamIn_V_V_0_state == 2'd2) & (dataStreamIn_V_V_0_vld_in == 1'b0)) | ((dataStreamIn_V_V_0_state == 2'd3) & (dataStreamIn_V_V_0_vld_in == 1'b0) & (dataStreamIn_V_V_0_ack_out == 1'b1)))) begin
            dataStreamIn_V_V_0_state <= 2'd2;
        end else if ((((dataStreamIn_V_V_0_state == 2'd1) & (dataStreamIn_V_V_0_ack_out == 1'b0)) | ((dataStreamIn_V_V_0_state == 2'd3) & (dataStreamIn_V_V_0_ack_out == 1'b0) & (dataStreamIn_V_V_0_vld_in == 1'b1)))) begin
            dataStreamIn_V_V_0_state <= 2'd1;
        end else if (((~((dataStreamIn_V_V_0_vld_in == 1'b0) & (dataStreamIn_V_V_0_ack_out == 1'b1)) & ~((dataStreamIn_V_V_0_ack_out == 1'b0) & (dataStreamIn_V_V_0_vld_in == 1'b1)) & (dataStreamIn_V_V_0_state == 2'd3)) | ((dataStreamIn_V_V_0_state == 2'd1) & (dataStreamIn_V_V_0_ack_out == 1'b1)) | ((dataStreamIn_V_V_0_state == 2'd2) & (dataStreamIn_V_V_0_vld_in == 1'b1)))) begin
            dataStreamIn_V_V_0_state <= 2'd3;
        end else begin
            dataStreamIn_V_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_data_V_1_ack_out == 1'b1) & (descriptor_out_V_data_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_data_V_1_sel_rd <= ~descriptor_out_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_data_V_1_ack_in == 1'b1) & (descriptor_out_V_data_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_data_V_1_sel_wr <= ~descriptor_out_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_data_V_1_state == 2'd2) & (descriptor_out_V_data_V_1_vld_in == 1'b0)) | ((descriptor_out_V_data_V_1_state == 2'd3) & (descriptor_out_V_data_V_1_vld_in == 1'b0) & (descriptor_out_V_data_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_data_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_data_V_1_state == 2'd1) & (descriptor_out_V_data_V_1_ack_out == 1'b0)) | ((descriptor_out_V_data_V_1_state == 2'd3) & (descriptor_out_V_data_V_1_ack_out == 1'b0) & (descriptor_out_V_data_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_data_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_data_V_1_vld_in == 1'b0) & (descriptor_out_V_data_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_data_V_1_ack_out == 1'b0) & (descriptor_out_V_data_V_1_vld_in == 1'b1)) & (descriptor_out_V_data_V_1_state == 2'd3)) | ((descriptor_out_V_data_V_1_state == 2'd1) & (descriptor_out_V_data_V_1_ack_out == 1'b1)) | ((descriptor_out_V_data_V_1_state == 2'd2) & (descriptor_out_V_data_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_data_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_dest_V_1_ack_out == 1'b1) & (descriptor_out_V_dest_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_dest_V_1_sel_rd <= ~descriptor_out_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_dest_V_1_ack_in == 1'b1) & (descriptor_out_V_dest_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_dest_V_1_sel_wr <= ~descriptor_out_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_dest_V_1_state == 2'd2) & (descriptor_out_V_dest_V_1_vld_in == 1'b0)) | ((descriptor_out_V_dest_V_1_state == 2'd3) & (descriptor_out_V_dest_V_1_vld_in == 1'b0) & (descriptor_out_V_dest_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_dest_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_dest_V_1_state == 2'd1) & (descriptor_out_V_dest_V_1_ack_out == 1'b0)) | ((descriptor_out_V_dest_V_1_state == 2'd3) & (descriptor_out_V_dest_V_1_ack_out == 1'b0) & (descriptor_out_V_dest_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_dest_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_dest_V_1_vld_in == 1'b0) & (descriptor_out_V_dest_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_dest_V_1_ack_out == 1'b0) & (descriptor_out_V_dest_V_1_vld_in == 1'b1)) & (descriptor_out_V_dest_V_1_state == 2'd3)) | ((descriptor_out_V_dest_V_1_state == 2'd1) & (descriptor_out_V_dest_V_1_ack_out == 1'b1)) | ((descriptor_out_V_dest_V_1_state == 2'd2) & (descriptor_out_V_dest_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_dest_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_id_V_1_ack_out == 1'b1) & (descriptor_out_V_id_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_id_V_1_sel_rd <= ~descriptor_out_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_id_V_1_ack_in == 1'b1) & (descriptor_out_V_id_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_id_V_1_sel_wr <= ~descriptor_out_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_id_V_1_state == 2'd2) & (descriptor_out_V_id_V_1_vld_in == 1'b0)) | ((descriptor_out_V_id_V_1_state == 2'd3) & (descriptor_out_V_id_V_1_vld_in == 1'b0) & (descriptor_out_V_id_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_id_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_id_V_1_state == 2'd1) & (descriptor_out_V_id_V_1_ack_out == 1'b0)) | ((descriptor_out_V_id_V_1_state == 2'd3) & (descriptor_out_V_id_V_1_ack_out == 1'b0) & (descriptor_out_V_id_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_id_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_id_V_1_vld_in == 1'b0) & (descriptor_out_V_id_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_id_V_1_ack_out == 1'b0) & (descriptor_out_V_id_V_1_vld_in == 1'b1)) & (descriptor_out_V_id_V_1_state == 2'd3)) | ((descriptor_out_V_id_V_1_state == 2'd1) & (descriptor_out_V_id_V_1_ack_out == 1'b1)) | ((descriptor_out_V_id_V_1_state == 2'd2) & (descriptor_out_V_id_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_id_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_keep_V_1_ack_out == 1'b1) & (descriptor_out_V_keep_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_keep_V_1_sel_rd <= ~descriptor_out_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_keep_V_1_ack_in == 1'b1) & (descriptor_out_V_keep_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_keep_V_1_sel_wr <= ~descriptor_out_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_keep_V_1_state == 2'd2) & (descriptor_out_V_keep_V_1_vld_in == 1'b0)) | ((descriptor_out_V_keep_V_1_state == 2'd3) & (descriptor_out_V_keep_V_1_vld_in == 1'b0) & (descriptor_out_V_keep_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_keep_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_keep_V_1_state == 2'd1) & (descriptor_out_V_keep_V_1_ack_out == 1'b0)) | ((descriptor_out_V_keep_V_1_state == 2'd3) & (descriptor_out_V_keep_V_1_ack_out == 1'b0) & (descriptor_out_V_keep_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_keep_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_keep_V_1_vld_in == 1'b0) & (descriptor_out_V_keep_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_keep_V_1_ack_out == 1'b0) & (descriptor_out_V_keep_V_1_vld_in == 1'b1)) & (descriptor_out_V_keep_V_1_state == 2'd3)) | ((descriptor_out_V_keep_V_1_state == 2'd1) & (descriptor_out_V_keep_V_1_ack_out == 1'b1)) | ((descriptor_out_V_keep_V_1_state == 2'd2) & (descriptor_out_V_keep_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_keep_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_last_V_1_ack_out == 1'b1) & (descriptor_out_V_last_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_last_V_1_sel_rd <= ~descriptor_out_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_last_V_1_ack_in == 1'b1) & (descriptor_out_V_last_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_last_V_1_sel_wr <= ~descriptor_out_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_last_V_1_state == 2'd2) & (descriptor_out_V_last_V_1_vld_in == 1'b0)) | ((descriptor_out_V_last_V_1_state == 2'd3) & (descriptor_out_V_last_V_1_vld_in == 1'b0) & (descriptor_out_V_last_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_last_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_last_V_1_state == 2'd1) & (descriptor_out_V_last_V_1_ack_out == 1'b0)) | ((descriptor_out_V_last_V_1_state == 2'd3) & (descriptor_out_V_last_V_1_ack_out == 1'b0) & (descriptor_out_V_last_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_last_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_last_V_1_vld_in == 1'b0) & (descriptor_out_V_last_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_last_V_1_ack_out == 1'b0) & (descriptor_out_V_last_V_1_vld_in == 1'b1)) & (descriptor_out_V_last_V_1_state == 2'd3)) | ((descriptor_out_V_last_V_1_state == 2'd1) & (descriptor_out_V_last_V_1_ack_out == 1'b1)) | ((descriptor_out_V_last_V_1_state == 2'd2) & (descriptor_out_V_last_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_last_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_strb_V_1_ack_out == 1'b1) & (descriptor_out_V_strb_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_strb_V_1_sel_rd <= ~descriptor_out_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_strb_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_strb_V_1_ack_in == 1'b1) & (descriptor_out_V_strb_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_strb_V_1_sel_wr <= ~descriptor_out_V_strb_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_strb_V_1_state == 2'd2) & (descriptor_out_V_strb_V_1_vld_in == 1'b0)) | ((descriptor_out_V_strb_V_1_state == 2'd3) & (descriptor_out_V_strb_V_1_vld_in == 1'b0) & (descriptor_out_V_strb_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_strb_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_strb_V_1_state == 2'd1) & (descriptor_out_V_strb_V_1_ack_out == 1'b0)) | ((descriptor_out_V_strb_V_1_state == 2'd3) & (descriptor_out_V_strb_V_1_ack_out == 1'b0) & (descriptor_out_V_strb_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_strb_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_strb_V_1_vld_in == 1'b0) & (descriptor_out_V_strb_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_strb_V_1_ack_out == 1'b0) & (descriptor_out_V_strb_V_1_vld_in == 1'b1)) & (descriptor_out_V_strb_V_1_state == 2'd3)) | ((descriptor_out_V_strb_V_1_state == 2'd1) & (descriptor_out_V_strb_V_1_ack_out == 1'b1)) | ((descriptor_out_V_strb_V_1_state == 2'd2) & (descriptor_out_V_strb_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_strb_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((descriptor_out_V_user_V_1_ack_out == 1'b1) & (descriptor_out_V_user_V_1_vld_out == 1'b1))) begin
            descriptor_out_V_user_V_1_sel_rd <= ~descriptor_out_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((descriptor_out_V_user_V_1_ack_in == 1'b1) & (descriptor_out_V_user_V_1_vld_in == 1'b1))) begin
            descriptor_out_V_user_V_1_sel_wr <= ~descriptor_out_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        descriptor_out_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((descriptor_out_V_user_V_1_state == 2'd2) & (descriptor_out_V_user_V_1_vld_in == 1'b0)) | ((descriptor_out_V_user_V_1_state == 2'd3) & (descriptor_out_V_user_V_1_vld_in == 1'b0) & (descriptor_out_V_user_V_1_ack_out == 1'b1)))) begin
            descriptor_out_V_user_V_1_state <= 2'd2;
        end else if ((((descriptor_out_V_user_V_1_state == 2'd1) & (descriptor_out_V_user_V_1_ack_out == 1'b0)) | ((descriptor_out_V_user_V_1_state == 2'd3) & (descriptor_out_V_user_V_1_ack_out == 1'b0) & (descriptor_out_V_user_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_user_V_1_state <= 2'd1;
        end else if (((~((descriptor_out_V_user_V_1_vld_in == 1'b0) & (descriptor_out_V_user_V_1_ack_out == 1'b1)) & ~((descriptor_out_V_user_V_1_ack_out == 1'b0) & (descriptor_out_V_user_V_1_vld_in == 1'b1)) & (descriptor_out_V_user_V_1_state == 2'd3)) | ((descriptor_out_V_user_V_1_state == 2'd1) & (descriptor_out_V_user_V_1_ack_out == 1'b1)) | ((descriptor_out_V_user_V_1_state == 2'd2) & (descriptor_out_V_user_V_1_vld_in == 1'b1)))) begin
            descriptor_out_V_user_V_1_state <= 2'd3;
        end else begin
            descriptor_out_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_windowSlider_fu_112_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_windowSlider_fu_112_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_windowSlider_fu_112_ap_start_reg <= 1'b1;
        end else if ((grp_windowSlider_fu_112_ap_ready == 1'b1)) begin
            grp_windowSlider_fu_112_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        srcStream_V_V_0_sel_rd <= 1'b0;
    end else begin
        if (((srcStream_V_V_0_ack_out == 1'b1) & (srcStream_V_V_0_vld_out == 1'b1))) begin
            srcStream_V_V_0_sel_rd <= ~srcStream_V_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        srcStream_V_V_0_sel_wr <= 1'b0;
    end else begin
        if (((srcStream_V_V_0_ack_in == 1'b1) & (srcStream_V_V_0_vld_in == 1'b1))) begin
            srcStream_V_V_0_sel_wr <= ~srcStream_V_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        srcStream_V_V_0_state <= 2'd0;
    end else begin
        if ((((srcStream_V_V_0_state == 2'd2) & (srcStream_V_V_0_vld_in == 1'b0)) | ((srcStream_V_V_0_state == 2'd3) & (srcStream_V_V_0_vld_in == 1'b0) & (srcStream_V_V_0_ack_out == 1'b1)))) begin
            srcStream_V_V_0_state <= 2'd2;
        end else if ((((srcStream_V_V_0_state == 2'd1) & (srcStream_V_V_0_ack_out == 1'b0)) | ((srcStream_V_V_0_state == 2'd3) & (srcStream_V_V_0_ack_out == 1'b0) & (srcStream_V_V_0_vld_in == 1'b1)))) begin
            srcStream_V_V_0_state <= 2'd1;
        end else if (((~((srcStream_V_V_0_vld_in == 1'b0) & (srcStream_V_V_0_ack_out == 1'b1)) & ~((srcStream_V_V_0_ack_out == 1'b0) & (srcStream_V_V_0_vld_in == 1'b1)) & (srcStream_V_V_0_state == 2'd3)) | ((srcStream_V_V_0_state == 2'd1) & (srcStream_V_V_0_ack_out == 1'b1)) | ((srcStream_V_V_0_state == 2'd2) & (srcStream_V_V_0_vld_in == 1'b1)))) begin
            srcStream_V_V_0_state <= 2'd3;
        end else begin
            srcStream_V_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((dataStreamIn_V_V_0_load_A == 1'b1)) begin
        dataStreamIn_V_V_0_payload_A <= dataStreamIn_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((dataStreamIn_V_V_0_load_B == 1'b1)) begin
        dataStreamIn_V_V_0_payload_B <= dataStreamIn_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_data_V_1_load_A == 1'b1)) begin
        descriptor_out_V_data_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_data_V_1_load_B == 1'b1)) begin
        descriptor_out_V_data_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_dest_V_1_load_A == 1'b1)) begin
        descriptor_out_V_dest_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_dest_V_1_load_B == 1'b1)) begin
        descriptor_out_V_dest_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_id_V_1_load_A == 1'b1)) begin
        descriptor_out_V_id_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_id_V_1_load_B == 1'b1)) begin
        descriptor_out_V_id_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_keep_V_1_load_A == 1'b1)) begin
        descriptor_out_V_keep_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_keep_V_1_load_B == 1'b1)) begin
        descriptor_out_V_keep_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_last_V_1_load_A == 1'b1)) begin
        descriptor_out_V_last_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_last_V_1_load_B == 1'b1)) begin
        descriptor_out_V_last_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_strb_V_1_load_A == 1'b1)) begin
        descriptor_out_V_strb_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_strb_V_1_load_B == 1'b1)) begin
        descriptor_out_V_strb_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_user_V_1_load_A == 1'b1)) begin
        descriptor_out_V_user_V_1_payload_A <= grp_windowSlider_fu_112_descriptor_out_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((descriptor_out_V_user_V_1_load_B == 1'b1)) begin
        descriptor_out_V_user_V_1_payload_B <= grp_windowSlider_fu_112_descriptor_out_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        extLd1_cast_reg_193[9 : 0] <= extLd1_cast_fu_164_p1[9 : 0];
        extLd_cast_reg_188[8 : 0] <= extLd_cast_fu_160_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_image_height_load_reg_178 <= p_image_height_q0;
        p_image_width_load_reg_183 <= p_image_width_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((srcStream_V_V_0_load_A == 1'b1)) begin
        srcStream_V_V_0_payload_A <= srcStream_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((srcStream_V_V_0_load_B == 1'b1)) begin
        srcStream_V_V_0_payload_B <= srcStream_V_V_TDATA;
    end
end

always @ (*) begin
    if ((~((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dataStreamIn_V_V_0_ack_out = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dataStreamIn_V_V_0_ack_out = grp_windowSlider_fu_112_dataPackStreamIn_V_V_TREADY;
    end else begin
        dataStreamIn_V_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((dataStreamIn_V_V_0_sel == 1'b1)) begin
        dataStreamIn_V_V_0_data_out = dataStreamIn_V_V_0_payload_B;
    end else begin
        dataStreamIn_V_V_0_data_out = dataStreamIn_V_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        dataStreamIn_V_V_TDATA_blk_n = dataStreamIn_V_V_0_state[1'd0];
    end else begin
        dataStreamIn_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((descriptor_out_V_data_V_1_sel == 1'b1)) begin
        descriptor_out_V_data_V_1_data_out = descriptor_out_V_data_V_1_payload_B;
    end else begin
        descriptor_out_V_data_V_1_data_out = descriptor_out_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_dest_V_1_sel == 1'b1)) begin
        descriptor_out_V_dest_V_1_data_out = descriptor_out_V_dest_V_1_payload_B;
    end else begin
        descriptor_out_V_dest_V_1_data_out = descriptor_out_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_id_V_1_sel == 1'b1)) begin
        descriptor_out_V_id_V_1_data_out = descriptor_out_V_id_V_1_payload_B;
    end else begin
        descriptor_out_V_id_V_1_data_out = descriptor_out_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_keep_V_1_sel == 1'b1)) begin
        descriptor_out_V_keep_V_1_data_out = descriptor_out_V_keep_V_1_payload_B;
    end else begin
        descriptor_out_V_keep_V_1_data_out = descriptor_out_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_last_V_1_sel == 1'b1)) begin
        descriptor_out_V_last_V_1_data_out = descriptor_out_V_last_V_1_payload_B;
    end else begin
        descriptor_out_V_last_V_1_data_out = descriptor_out_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_strb_V_1_sel == 1'b1)) begin
        descriptor_out_V_strb_V_1_data_out = descriptor_out_V_strb_V_1_payload_B;
    end else begin
        descriptor_out_V_strb_V_1_data_out = descriptor_out_V_strb_V_1_payload_A;
    end
end

always @ (*) begin
    if ((descriptor_out_V_user_V_1_sel == 1'b1)) begin
        descriptor_out_V_user_V_1_data_out = descriptor_out_V_user_V_1_payload_B;
    end else begin
        descriptor_out_V_user_V_1_data_out = descriptor_out_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_windowSlider_fu_112_ap_continue = 1'b1;
    end else begin
        grp_windowSlider_fu_112_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((~((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_height_ce0 = 1'b1;
    end else begin
        p_image_height_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_image_width_ce0 = 1'b1;
    end else begin
        p_image_width_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        srcStream_V_V_0_ack_out = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        srcStream_V_V_0_ack_out = grp_windowSlider_fu_112_src_V_V_TREADY;
    end else begin
        srcStream_V_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((srcStream_V_V_0_sel == 1'b1)) begin
        srcStream_V_V_0_data_out = srcStream_V_V_0_payload_B;
    end else begin
        srcStream_V_V_0_data_out = srcStream_V_V_0_payload_A;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        srcStream_V_V_TDATA_blk_n = srcStream_V_V_0_state[1'd0];
    end else begin
        srcStream_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((descriptor_out_V_dest_V_1_ack_in == 1'b0) | (descriptor_out_V_id_V_1_ack_in == 1'b0) | (descriptor_out_V_last_V_1_ack_in == 1'b0) | (descriptor_out_V_user_V_1_ack_in == 1'b0) | (descriptor_out_V_strb_V_1_ack_in == 1'b0) | (descriptor_out_V_keep_V_1_ack_in == 1'b0) | (descriptor_out_V_data_V_1_ack_in == 1'b0)) & (descriptor_out_V_dest_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_id_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_last_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_user_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_strb_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_keep_V_1_state[1'd0] == 1'b0) & (descriptor_out_V_data_V_1_state[1'd0] == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((dataStreamIn_V_V_0_vld_out == 1'b0) | (srcStream_V_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_grp_windowSlider_fu_112_ap_ready & ap_sync_grp_windowSlider_fu_112_ap_done) == 1'b0);
end

always @ (*) begin
    ap_block_state5 = ((descriptor_out_V_dest_V_1_ack_in == 1'b0) | (descriptor_out_V_id_V_1_ack_in == 1'b0) | (descriptor_out_V_last_V_1_ack_in == 1'b0) | (descriptor_out_V_user_V_1_ack_in == 1'b0) | (descriptor_out_V_strb_V_1_ack_in == 1'b0) | (descriptor_out_V_keep_V_1_ack_in == 1'b0) | (descriptor_out_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_windowSlider_fu_112_ap_done = (grp_windowSlider_fu_112_ap_done | ap_sync_reg_grp_windowSlider_fu_112_ap_done);

assign ap_sync_grp_windowSlider_fu_112_ap_ready = (grp_windowSlider_fu_112_ap_ready | ap_sync_reg_grp_windowSlider_fu_112_ap_ready);

assign dataStreamIn_V_V_0_ack_in = dataStreamIn_V_V_0_state[1'd1];

assign dataStreamIn_V_V_0_load_A = (~dataStreamIn_V_V_0_sel_wr & dataStreamIn_V_V_0_state_cmp_full);

assign dataStreamIn_V_V_0_load_B = (dataStreamIn_V_V_0_state_cmp_full & dataStreamIn_V_V_0_sel_wr);

assign dataStreamIn_V_V_0_sel = dataStreamIn_V_V_0_sel_rd;

assign dataStreamIn_V_V_0_state_cmp_full = ((dataStreamIn_V_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign dataStreamIn_V_V_0_vld_in = dataStreamIn_V_V_TVALID;

assign dataStreamIn_V_V_0_vld_out = dataStreamIn_V_V_0_state[1'd0];

assign dataStreamIn_V_V_TREADY = dataStreamIn_V_V_0_state[1'd1];

assign descriptor_out_TDATA = descriptor_out_V_data_V_1_data_out;

assign descriptor_out_TDEST = descriptor_out_V_dest_V_1_data_out;

assign descriptor_out_TID = descriptor_out_V_id_V_1_data_out;

assign descriptor_out_TKEEP = descriptor_out_V_keep_V_1_data_out;

assign descriptor_out_TLAST = descriptor_out_V_last_V_1_data_out;

assign descriptor_out_TSTRB = descriptor_out_V_strb_V_1_data_out;

assign descriptor_out_TUSER = descriptor_out_V_user_V_1_data_out;

assign descriptor_out_TVALID = descriptor_out_V_dest_V_1_state[1'd0];

assign descriptor_out_V_data_V_1_ack_in = descriptor_out_V_data_V_1_state[1'd1];

assign descriptor_out_V_data_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_data_V_1_load_A = (~descriptor_out_V_data_V_1_sel_wr & descriptor_out_V_data_V_1_state_cmp_full);

assign descriptor_out_V_data_V_1_load_B = (descriptor_out_V_data_V_1_state_cmp_full & descriptor_out_V_data_V_1_sel_wr);

assign descriptor_out_V_data_V_1_sel = descriptor_out_V_data_V_1_sel_rd;

assign descriptor_out_V_data_V_1_state_cmp_full = ((descriptor_out_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_data_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_data_V_1_vld_out = descriptor_out_V_data_V_1_state[1'd0];

assign descriptor_out_V_dest_V_1_ack_in = descriptor_out_V_dest_V_1_state[1'd1];

assign descriptor_out_V_dest_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_dest_V_1_load_A = (~descriptor_out_V_dest_V_1_sel_wr & descriptor_out_V_dest_V_1_state_cmp_full);

assign descriptor_out_V_dest_V_1_load_B = (descriptor_out_V_dest_V_1_state_cmp_full & descriptor_out_V_dest_V_1_sel_wr);

assign descriptor_out_V_dest_V_1_sel = descriptor_out_V_dest_V_1_sel_rd;

assign descriptor_out_V_dest_V_1_state_cmp_full = ((descriptor_out_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_dest_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_dest_V_1_vld_out = descriptor_out_V_dest_V_1_state[1'd0];

assign descriptor_out_V_id_V_1_ack_in = descriptor_out_V_id_V_1_state[1'd1];

assign descriptor_out_V_id_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_id_V_1_load_A = (~descriptor_out_V_id_V_1_sel_wr & descriptor_out_V_id_V_1_state_cmp_full);

assign descriptor_out_V_id_V_1_load_B = (descriptor_out_V_id_V_1_state_cmp_full & descriptor_out_V_id_V_1_sel_wr);

assign descriptor_out_V_id_V_1_sel = descriptor_out_V_id_V_1_sel_rd;

assign descriptor_out_V_id_V_1_state_cmp_full = ((descriptor_out_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_id_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_id_V_1_vld_out = descriptor_out_V_id_V_1_state[1'd0];

assign descriptor_out_V_keep_V_1_ack_in = descriptor_out_V_keep_V_1_state[1'd1];

assign descriptor_out_V_keep_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_keep_V_1_load_A = (~descriptor_out_V_keep_V_1_sel_wr & descriptor_out_V_keep_V_1_state_cmp_full);

assign descriptor_out_V_keep_V_1_load_B = (descriptor_out_V_keep_V_1_state_cmp_full & descriptor_out_V_keep_V_1_sel_wr);

assign descriptor_out_V_keep_V_1_sel = descriptor_out_V_keep_V_1_sel_rd;

assign descriptor_out_V_keep_V_1_state_cmp_full = ((descriptor_out_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_keep_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_keep_V_1_vld_out = descriptor_out_V_keep_V_1_state[1'd0];

assign descriptor_out_V_last_V_1_ack_in = descriptor_out_V_last_V_1_state[1'd1];

assign descriptor_out_V_last_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_last_V_1_load_A = (~descriptor_out_V_last_V_1_sel_wr & descriptor_out_V_last_V_1_state_cmp_full);

assign descriptor_out_V_last_V_1_load_B = (descriptor_out_V_last_V_1_state_cmp_full & descriptor_out_V_last_V_1_sel_wr);

assign descriptor_out_V_last_V_1_sel = descriptor_out_V_last_V_1_sel_rd;

assign descriptor_out_V_last_V_1_state_cmp_full = ((descriptor_out_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_last_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_last_V_1_vld_out = descriptor_out_V_last_V_1_state[1'd0];

assign descriptor_out_V_strb_V_1_ack_in = descriptor_out_V_strb_V_1_state[1'd1];

assign descriptor_out_V_strb_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_strb_V_1_load_A = (~descriptor_out_V_strb_V_1_sel_wr & descriptor_out_V_strb_V_1_state_cmp_full);

assign descriptor_out_V_strb_V_1_load_B = (descriptor_out_V_strb_V_1_state_cmp_full & descriptor_out_V_strb_V_1_sel_wr);

assign descriptor_out_V_strb_V_1_sel = descriptor_out_V_strb_V_1_sel_rd;

assign descriptor_out_V_strb_V_1_state_cmp_full = ((descriptor_out_V_strb_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_strb_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_strb_V_1_vld_out = descriptor_out_V_strb_V_1_state[1'd0];

assign descriptor_out_V_user_V_1_ack_in = descriptor_out_V_user_V_1_state[1'd1];

assign descriptor_out_V_user_V_1_ack_out = descriptor_out_TREADY;

assign descriptor_out_V_user_V_1_load_A = (~descriptor_out_V_user_V_1_sel_wr & descriptor_out_V_user_V_1_state_cmp_full);

assign descriptor_out_V_user_V_1_load_B = (descriptor_out_V_user_V_1_state_cmp_full & descriptor_out_V_user_V_1_sel_wr);

assign descriptor_out_V_user_V_1_sel = descriptor_out_V_user_V_1_sel_rd;

assign descriptor_out_V_user_V_1_state_cmp_full = ((descriptor_out_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign descriptor_out_V_user_V_1_vld_in = grp_windowSlider_fu_112_descriptor_out_TVALID;

assign descriptor_out_V_user_V_1_vld_out = descriptor_out_V_user_V_1_state[1'd0];

assign extLd1_cast_fu_164_p1 = p_image_width_load_reg_183;

assign extLd_cast_fu_160_p1 = p_image_height_load_reg_178;

assign grp_windowSlider_fu_112_ap_start = grp_windowSlider_fu_112_ap_start_reg;

assign grp_windowSlider_fu_112_dataPackStreamIn_V_V_TVALID = dataStreamIn_V_V_0_state[1'd0];

assign grp_windowSlider_fu_112_descriptor_out_TREADY = ((descriptor_out_V_dest_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_id_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_last_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_user_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_strb_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_keep_V_1_ack_in & ap_CS_fsm_state4) | (descriptor_out_V_data_V_1_ack_in & ap_CS_fsm_state4));

assign grp_windowSlider_fu_112_src_V_V_TVALID = srcStream_V_V_0_state[1'd0];

assign p_image_height_address0 = tmp_fu_154_p1;

assign p_image_width_address0 = tmp_fu_154_p1;

assign srcStream_V_V_0_ack_in = srcStream_V_V_0_state[1'd1];

assign srcStream_V_V_0_load_A = (srcStream_V_V_0_state_cmp_full & ~srcStream_V_V_0_sel_wr);

assign srcStream_V_V_0_load_B = (srcStream_V_V_0_state_cmp_full & srcStream_V_V_0_sel_wr);

assign srcStream_V_V_0_sel = srcStream_V_V_0_sel_rd;

assign srcStream_V_V_0_state_cmp_full = ((srcStream_V_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign srcStream_V_V_0_vld_in = srcStream_V_V_TVALID;

assign srcStream_V_V_0_vld_out = srcStream_V_V_0_state[1'd0];

assign srcStream_V_V_TREADY = srcStream_V_V_0_state[1'd1];

assign tmp_fu_154_p1 = srcStream_V_V_0_data_out;

always @ (posedge ap_clk) begin
    extLd_cast_reg_188[10:9] <= 2'b00;
    extLd1_cast_reg_193[11:10] <= 2'b00;
end

endmodule //comDescriptor_accel
