// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module windowSlider (
        src_V_V_TDATA,
        dataPackStreamIn_V_V_TDATA,
        descriptor_out_TDATA,
        descriptor_out_TKEEP,
        descriptor_out_TSTRB,
        descriptor_out_TUSER,
        descriptor_out_TLAST,
        descriptor_out_TID,
        descriptor_out_TDEST,
        p_image_height,
        p_image_width,
        ap_clk,
        ap_rst,
        src_V_V_TVALID,
        src_V_V_TREADY,
        dataPackStreamIn_V_V_TVALID,
        dataPackStreamIn_V_V_TREADY,
        p_image_height_ap_vld,
        p_image_width_ap_vld,
        ap_start,
        descriptor_out_TVALID,
        descriptor_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] src_V_V_TDATA;
input  [87:0] dataPackStreamIn_V_V_TDATA;
output  [31:0] descriptor_out_TDATA;
output  [3:0] descriptor_out_TKEEP;
output  [3:0] descriptor_out_TSTRB;
output  [0:0] descriptor_out_TUSER;
output  [0:0] descriptor_out_TLAST;
output  [0:0] descriptor_out_TID;
output  [0:0] descriptor_out_TDEST;
input  [10:0] p_image_height;
input  [11:0] p_image_width;
input   ap_clk;
input   ap_rst;
input   src_V_V_TVALID;
output   src_V_V_TREADY;
input   dataPackStreamIn_V_V_TVALID;
output   dataPackStreamIn_V_V_TREADY;
input   p_image_height_ap_vld;
input   p_image_width_ap_vld;
input   ap_start;
output   descriptor_out_TVALID;
input   descriptor_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    windowSliderProc81_U0_ap_start;
wire    windowSliderProc81_U0_ap_done;
wire    windowSliderProc81_U0_ap_continue;
wire    windowSliderProc81_U0_ap_idle;
wire    windowSliderProc81_U0_ap_ready;
wire    windowSliderProc81_U0_start_out;
wire    windowSliderProc81_U0_start_write;
wire    windowSliderProc81_U0_src_V_V_TREADY;
wire    windowSliderProc81_U0_dataPackStreamIn_V_V_TREADY;
wire   [335:0] windowSliderProc81_U0_dataPackStream_V_V_din;
wire    windowSliderProc81_U0_dataPackStream_V_V_write;
wire   [8:0] windowSliderProc81_U0_p_image_height_c_din;
wire    windowSliderProc81_U0_p_image_height_c_write;
wire   [9:0] windowSliderProc81_U0_p_image_width_c_din;
wire    windowSliderProc81_U0_p_image_width_c_write;
wire    Descriptors_U0_ap_start;
wire    Descriptors_U0_ap_done;
wire    Descriptors_U0_ap_continue;
wire    Descriptors_U0_ap_idle;
wire    Descriptors_U0_ap_ready;
wire    Descriptors_U0_dataPackStreamIn_V_V_read;
wire   [31:0] Descriptors_U0_descriptor_out_TDATA;
wire    Descriptors_U0_descriptor_out_TVALID;
wire   [3:0] Descriptors_U0_descriptor_out_TKEEP;
wire   [3:0] Descriptors_U0_descriptor_out_TSTRB;
wire   [0:0] Descriptors_U0_descriptor_out_TUSER;
wire   [0:0] Descriptors_U0_descriptor_out_TLAST;
wire   [0:0] Descriptors_U0_descriptor_out_TID;
wire   [0:0] Descriptors_U0_descriptor_out_TDEST;
wire    Descriptors_U0_img_width_read;
wire    Descriptors_U0_img_height_read;
wire    Descriptors_U0_res_y0_V_V_read;
wire   [4:0] Descriptors_U0_res_y0_V_V_din;
wire    Descriptors_U0_res_y0_V_V_write;
wire    Descriptors_U0_res_x0_V_V_read;
wire   [4:0] Descriptors_U0_res_x0_V_V_din;
wire    Descriptors_U0_res_x0_V_V_write;
wire    Descriptors_U0_res_y1_V_V_read;
wire   [4:0] Descriptors_U0_res_y1_V_V_din;
wire    Descriptors_U0_res_y1_V_V_write;
wire    Descriptors_U0_res_x1_V_V_read;
wire   [4:0] Descriptors_U0_res_x1_V_V_din;
wire    Descriptors_U0_res_x1_V_V_write;
wire    ap_sync_continue;
wire    dataPackStream_V_V_full_n;
wire   [335:0] dataPackStream_V_V_dout;
wire    dataPackStream_V_V_empty_n;
wire    p_image_height_c_full_n;
wire   [8:0] p_image_height_c_dout;
wire    p_image_height_c_empty_n;
wire    p_image_width_c_full_n;
wire   [9:0] p_image_width_c_dout;
wire    p_image_width_c_empty_n;
wire    res_y0_V_V_full_n;
wire   [4:0] res_y0_V_V_dout;
wire    res_y0_V_V_empty_n;
wire    res_x0_V_V_full_n;
wire   [4:0] res_x0_V_V_dout;
wire    res_x0_V_V_empty_n;
wire    res_y1_V_V_full_n;
wire   [4:0] res_y1_V_V_dout;
wire    res_y1_V_V_empty_n;
wire    res_x1_V_V_full_n;
wire   [4:0] res_x1_V_V_dout;
wire    res_x1_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Descriptors_U0_din;
wire    start_for_Descriptors_U0_full_n;
wire   [0:0] start_for_Descriptors_U0_dout;
wire    start_for_Descriptors_U0_empty_n;
wire    Descriptors_U0_start_full_n;
wire    Descriptors_U0_start_write;

windowSliderProc81 windowSliderProc81_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(windowSliderProc81_U0_ap_start),
    .start_full_n(start_for_Descriptors_U0_full_n),
    .ap_done(windowSliderProc81_U0_ap_done),
    .ap_continue(windowSliderProc81_U0_ap_continue),
    .ap_idle(windowSliderProc81_U0_ap_idle),
    .ap_ready(windowSliderProc81_U0_ap_ready),
    .start_out(windowSliderProc81_U0_start_out),
    .start_write(windowSliderProc81_U0_start_write),
    .src_V_V_TDATA(src_V_V_TDATA),
    .src_V_V_TVALID(src_V_V_TVALID),
    .src_V_V_TREADY(windowSliderProc81_U0_src_V_V_TREADY),
    .dataPackStreamIn_V_V_TDATA(dataPackStreamIn_V_V_TDATA),
    .dataPackStreamIn_V_V_TVALID(dataPackStreamIn_V_V_TVALID),
    .dataPackStreamIn_V_V_TREADY(windowSliderProc81_U0_dataPackStreamIn_V_V_TREADY),
    .dataPackStream_V_V_din(windowSliderProc81_U0_dataPackStream_V_V_din),
    .dataPackStream_V_V_full_n(dataPackStream_V_V_full_n),
    .dataPackStream_V_V_write(windowSliderProc81_U0_dataPackStream_V_V_write),
    .p_image_height(p_image_height),
    .p_image_width(p_image_width),
    .p_image_height_c_din(windowSliderProc81_U0_p_image_height_c_din),
    .p_image_height_c_full_n(p_image_height_c_full_n),
    .p_image_height_c_write(windowSliderProc81_U0_p_image_height_c_write),
    .p_image_width_c_din(windowSliderProc81_U0_p_image_width_c_din),
    .p_image_width_c_full_n(p_image_width_c_full_n),
    .p_image_width_c_write(windowSliderProc81_U0_p_image_width_c_write)
);

Descriptors Descriptors_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Descriptors_U0_ap_start),
    .ap_done(Descriptors_U0_ap_done),
    .ap_continue(Descriptors_U0_ap_continue),
    .ap_idle(Descriptors_U0_ap_idle),
    .ap_ready(Descriptors_U0_ap_ready),
    .dataPackStreamIn_V_V_dout(dataPackStream_V_V_dout),
    .dataPackStreamIn_V_V_empty_n(dataPackStream_V_V_empty_n),
    .dataPackStreamIn_V_V_read(Descriptors_U0_dataPackStreamIn_V_V_read),
    .descriptor_out_TDATA(Descriptors_U0_descriptor_out_TDATA),
    .descriptor_out_TVALID(Descriptors_U0_descriptor_out_TVALID),
    .descriptor_out_TREADY(descriptor_out_TREADY),
    .descriptor_out_TKEEP(Descriptors_U0_descriptor_out_TKEEP),
    .descriptor_out_TSTRB(Descriptors_U0_descriptor_out_TSTRB),
    .descriptor_out_TUSER(Descriptors_U0_descriptor_out_TUSER),
    .descriptor_out_TLAST(Descriptors_U0_descriptor_out_TLAST),
    .descriptor_out_TID(Descriptors_U0_descriptor_out_TID),
    .descriptor_out_TDEST(Descriptors_U0_descriptor_out_TDEST),
    .img_width_dout(p_image_width_c_dout),
    .img_width_empty_n(p_image_width_c_empty_n),
    .img_width_read(Descriptors_U0_img_width_read),
    .img_height_dout(p_image_height_c_dout),
    .img_height_empty_n(p_image_height_c_empty_n),
    .img_height_read(Descriptors_U0_img_height_read),
    .res_y0_V_V_dout(res_y0_V_V_dout),
    .res_y0_V_V_empty_n(res_y0_V_V_empty_n),
    .res_y0_V_V_read(Descriptors_U0_res_y0_V_V_read),
    .res_y0_V_V_din(Descriptors_U0_res_y0_V_V_din),
    .res_y0_V_V_full_n(res_y0_V_V_full_n),
    .res_y0_V_V_write(Descriptors_U0_res_y0_V_V_write),
    .res_x0_V_V_dout(res_x0_V_V_dout),
    .res_x0_V_V_empty_n(res_x0_V_V_empty_n),
    .res_x0_V_V_read(Descriptors_U0_res_x0_V_V_read),
    .res_x0_V_V_din(Descriptors_U0_res_x0_V_V_din),
    .res_x0_V_V_full_n(res_x0_V_V_full_n),
    .res_x0_V_V_write(Descriptors_U0_res_x0_V_V_write),
    .res_y1_V_V_dout(res_y1_V_V_dout),
    .res_y1_V_V_empty_n(res_y1_V_V_empty_n),
    .res_y1_V_V_read(Descriptors_U0_res_y1_V_V_read),
    .res_y1_V_V_din(Descriptors_U0_res_y1_V_V_din),
    .res_y1_V_V_full_n(res_y1_V_V_full_n),
    .res_y1_V_V_write(Descriptors_U0_res_y1_V_V_write),
    .res_x1_V_V_dout(res_x1_V_V_dout),
    .res_x1_V_V_empty_n(res_x1_V_V_empty_n),
    .res_x1_V_V_read(Descriptors_U0_res_x1_V_V_read),
    .res_x1_V_V_din(Descriptors_U0_res_x1_V_V_din),
    .res_x1_V_V_full_n(res_x1_V_V_full_n),
    .res_x1_V_V_write(Descriptors_U0_res_x1_V_V_write)
);

fifo_w336_d2_A dataPackStream_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(windowSliderProc81_U0_dataPackStream_V_V_din),
    .if_full_n(dataPackStream_V_V_full_n),
    .if_write(windowSliderProc81_U0_dataPackStream_V_V_write),
    .if_dout(dataPackStream_V_V_dout),
    .if_empty_n(dataPackStream_V_V_empty_n),
    .if_read(Descriptors_U0_dataPackStreamIn_V_V_read)
);

fifo_w9_d2_A p_image_height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(windowSliderProc81_U0_p_image_height_c_din),
    .if_full_n(p_image_height_c_full_n),
    .if_write(windowSliderProc81_U0_p_image_height_c_write),
    .if_dout(p_image_height_c_dout),
    .if_empty_n(p_image_height_c_empty_n),
    .if_read(Descriptors_U0_img_height_read)
);

fifo_w10_d2_A p_image_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(windowSliderProc81_U0_p_image_width_c_din),
    .if_full_n(p_image_width_c_full_n),
    .if_write(windowSliderProc81_U0_p_image_width_c_write),
    .if_dout(p_image_width_c_dout),
    .if_empty_n(p_image_width_c_empty_n),
    .if_read(Descriptors_U0_img_width_read)
);

fifo_w5_d8_A res_y0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Descriptors_U0_res_y0_V_V_din),
    .if_full_n(res_y0_V_V_full_n),
    .if_write(Descriptors_U0_res_y0_V_V_write),
    .if_dout(res_y0_V_V_dout),
    .if_empty_n(res_y0_V_V_empty_n),
    .if_read(Descriptors_U0_res_y0_V_V_read)
);

fifo_w5_d8_A res_x0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Descriptors_U0_res_x0_V_V_din),
    .if_full_n(res_x0_V_V_full_n),
    .if_write(Descriptors_U0_res_x0_V_V_write),
    .if_dout(res_x0_V_V_dout),
    .if_empty_n(res_x0_V_V_empty_n),
    .if_read(Descriptors_U0_res_x0_V_V_read)
);

fifo_w5_d8_A res_y1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Descriptors_U0_res_y1_V_V_din),
    .if_full_n(res_y1_V_V_full_n),
    .if_write(Descriptors_U0_res_y1_V_V_write),
    .if_dout(res_y1_V_V_dout),
    .if_empty_n(res_y1_V_V_empty_n),
    .if_read(Descriptors_U0_res_y1_V_V_read)
);

fifo_w5_d8_A res_x1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Descriptors_U0_res_x1_V_V_din),
    .if_full_n(res_x1_V_V_full_n),
    .if_write(Descriptors_U0_res_x1_V_V_write),
    .if_dout(res_x1_V_V_dout),
    .if_empty_n(res_x1_V_V_empty_n),
    .if_read(Descriptors_U0_res_x1_V_V_read)
);

start_for_DescripVhK start_for_DescripVhK_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Descriptors_U0_din),
    .if_full_n(start_for_Descriptors_U0_full_n),
    .if_write(windowSliderProc81_U0_start_write),
    .if_dout(start_for_Descriptors_U0_dout),
    .if_empty_n(start_for_Descriptors_U0_empty_n),
    .if_read(Descriptors_U0_ap_ready)
);

assign Descriptors_U0_ap_continue = ap_continue;

assign Descriptors_U0_ap_start = start_for_Descriptors_U0_empty_n;

assign Descriptors_U0_start_full_n = 1'b1;

assign Descriptors_U0_start_write = 1'b0;

assign ap_done = Descriptors_U0_ap_done;

assign ap_idle = (windowSliderProc81_U0_ap_idle & Descriptors_U0_ap_idle);

assign ap_ready = windowSliderProc81_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = Descriptors_U0_ap_done;

assign ap_sync_ready = windowSliderProc81_U0_ap_ready;

assign dataPackStreamIn_V_V_TREADY = windowSliderProc81_U0_dataPackStreamIn_V_V_TREADY;

assign descriptor_out_TDATA = Descriptors_U0_descriptor_out_TDATA;

assign descriptor_out_TDEST = Descriptors_U0_descriptor_out_TDEST;

assign descriptor_out_TID = Descriptors_U0_descriptor_out_TID;

assign descriptor_out_TKEEP = Descriptors_U0_descriptor_out_TKEEP;

assign descriptor_out_TLAST = Descriptors_U0_descriptor_out_TLAST;

assign descriptor_out_TSTRB = Descriptors_U0_descriptor_out_TSTRB;

assign descriptor_out_TUSER = Descriptors_U0_descriptor_out_TUSER;

assign descriptor_out_TVALID = Descriptors_U0_descriptor_out_TVALID;

assign src_V_V_TREADY = windowSliderProc81_U0_src_V_V_TREADY;

assign start_for_Descriptors_U0_din = 1'b1;

assign windowSliderProc81_U0_ap_continue = 1'b1;

assign windowSliderProc81_U0_ap_start = ap_start;

endmodule //windowSlider
