set( CMAKE_SYSTEM_NAME Linux )
set( CMAKE_SYSTEM_PROCESSOR arm )
set( CMAKE_C_COMPILER arm-linux-gnueabihf-gcc )
set( CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++ )
set( CMAKE_INSTALL_PREFIX "/usr/local/arm")
set( PKG_CONFIG_LIBDIR "/usr/local/arm/lib/pkgconfig" )
set( CMAKE_FIND_ROOT_PATH "/usr/local/arm/" )
set( CMAKE_C_FLAGS "-Wl,-rpath-link=/usr/local/arm/")
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
