// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xfapplygaussian7x7 (
        ap_clk,
        ap_rst,
        src_buf1_0_V_read,
        src_buf1_1_V_read,
        src_buf1_2_V_read,
        src_buf1_3_V_read,
        src_buf1_4_V_read,
        src_buf1_5_V_read,
        src_buf1_6_V_read,
        src_buf2_0_V_read,
        src_buf2_1_V_read,
        src_buf2_2_V_read,
        src_buf2_3_V_read,
        src_buf2_4_V_read,
        src_buf2_5_V_read,
        src_buf2_6_V_read,
        src_buf3_0_V_read,
        src_buf3_1_V_read,
        src_buf3_2_V_read,
        src_buf3_3_V_read,
        src_buf3_4_V_read,
        src_buf3_5_V_read,
        src_buf3_6_V_read,
        src_buf4_0_V_read,
        src_buf4_1_V_read,
        src_buf4_2_V_read,
        src_buf4_3_V_read,
        src_buf4_4_V_read,
        src_buf4_5_V_read,
        src_buf4_6_V_read,
        src_buf5_0_V_read,
        src_buf5_1_V_read,
        src_buf5_2_V_read,
        src_buf5_3_V_read,
        src_buf5_4_V_read,
        src_buf5_5_V_read,
        src_buf5_6_V_read,
        src_buf6_0_V_read,
        src_buf6_1_V_read,
        src_buf6_2_V_read,
        src_buf6_3_V_read,
        src_buf6_4_V_read,
        src_buf6_5_V_read,
        src_buf6_6_V_read,
        src_buf7_0_V_read,
        src_buf7_1_V_read,
        src_buf7_2_V_read,
        src_buf7_3_V_read,
        src_buf7_4_V_read,
        src_buf7_5_V_read,
        src_buf7_6_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] src_buf1_0_V_read;
input  [7:0] src_buf1_1_V_read;
input  [7:0] src_buf1_2_V_read;
input  [7:0] src_buf1_3_V_read;
input  [7:0] src_buf1_4_V_read;
input  [7:0] src_buf1_5_V_read;
input  [7:0] src_buf1_6_V_read;
input  [7:0] src_buf2_0_V_read;
input  [7:0] src_buf2_1_V_read;
input  [7:0] src_buf2_2_V_read;
input  [7:0] src_buf2_3_V_read;
input  [7:0] src_buf2_4_V_read;
input  [7:0] src_buf2_5_V_read;
input  [7:0] src_buf2_6_V_read;
input  [7:0] src_buf3_0_V_read;
input  [7:0] src_buf3_1_V_read;
input  [7:0] src_buf3_2_V_read;
input  [7:0] src_buf3_3_V_read;
input  [7:0] src_buf3_4_V_read;
input  [7:0] src_buf3_5_V_read;
input  [7:0] src_buf3_6_V_read;
input  [7:0] src_buf4_0_V_read;
input  [7:0] src_buf4_1_V_read;
input  [7:0] src_buf4_2_V_read;
input  [7:0] src_buf4_3_V_read;
input  [7:0] src_buf4_4_V_read;
input  [7:0] src_buf4_5_V_read;
input  [7:0] src_buf4_6_V_read;
input  [7:0] src_buf5_0_V_read;
input  [7:0] src_buf5_1_V_read;
input  [7:0] src_buf5_2_V_read;
input  [7:0] src_buf5_3_V_read;
input  [7:0] src_buf5_4_V_read;
input  [7:0] src_buf5_5_V_read;
input  [7:0] src_buf5_6_V_read;
input  [7:0] src_buf6_0_V_read;
input  [7:0] src_buf6_1_V_read;
input  [7:0] src_buf6_2_V_read;
input  [7:0] src_buf6_3_V_read;
input  [7:0] src_buf6_4_V_read;
input  [7:0] src_buf6_5_V_read;
input  [7:0] src_buf6_6_V_read;
input  [7:0] src_buf7_0_V_read;
input  [7:0] src_buf7_1_V_read;
input  [7:0] src_buf7_2_V_read;
input  [7:0] src_buf7_3_V_read;
input  [7:0] src_buf7_4_V_read;
input  [7:0] src_buf7_5_V_read;
input  [7:0] src_buf7_6_V_read;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg   [7:0] src_buf7_6_V_read_1_reg_1287;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] src_buf7_6_V_read_1_reg_1287_pp0_iter1_reg;
reg   [7:0] src_buf7_5_V_read_1_reg_1292;
reg   [7:0] src_buf7_5_V_read_1_reg_1292_pp0_iter1_reg;
reg   [7:0] src_buf7_4_V_read_1_reg_1297;
reg   [7:0] src_buf7_4_V_read_1_reg_1297_pp0_iter1_reg;
reg   [7:0] src_buf7_3_V_read_1_reg_1302;
reg   [7:0] src_buf7_3_V_read_1_reg_1302_pp0_iter1_reg;
reg   [7:0] src_buf7_3_V_read_1_reg_1302_pp0_iter2_reg;
reg   [7:0] src_buf7_3_V_read_1_reg_1302_pp0_iter3_reg;
reg   [7:0] src_buf7_3_V_read_1_reg_1302_pp0_iter4_reg;
reg   [7:0] src_buf7_2_V_read_1_reg_1307;
reg   [7:0] src_buf7_1_V_read_1_reg_1312;
reg   [7:0] src_buf7_0_V_read_1_reg_1317;
reg   [7:0] src_buf6_6_V_read_1_reg_1322;
reg   [7:0] src_buf6_6_V_read_1_reg_1322_pp0_iter1_reg;
reg   [7:0] src_buf6_5_V_read_1_reg_1327;
reg   [7:0] src_buf6_5_V_read_1_reg_1327_pp0_iter1_reg;
reg   [7:0] src_buf6_4_V_read_1_reg_1332;
reg   [7:0] src_buf6_4_V_read_1_reg_1332_pp0_iter1_reg;
reg   [7:0] src_buf6_3_V_read_1_reg_1337;
reg   [7:0] src_buf6_3_V_read_1_reg_1337_pp0_iter1_reg;
reg   [7:0] src_buf6_3_V_read_1_reg_1337_pp0_iter2_reg;
reg   [7:0] src_buf6_3_V_read_1_reg_1337_pp0_iter3_reg;
reg   [7:0] src_buf6_3_V_read_1_reg_1337_pp0_iter4_reg;
reg   [7:0] src_buf6_2_V_read_1_reg_1342;
reg   [7:0] src_buf6_1_V_read_1_reg_1347;
reg   [7:0] src_buf6_0_V_read_1_reg_1352;
reg   [7:0] src_buf5_6_V_read_1_reg_1357;
reg   [7:0] src_buf5_6_V_read_1_reg_1357_pp0_iter1_reg;
reg   [7:0] src_buf5_5_V_read_1_reg_1362;
reg   [7:0] src_buf5_5_V_read_1_reg_1362_pp0_iter1_reg;
reg   [7:0] src_buf5_4_V_read_1_reg_1367;
reg   [7:0] src_buf5_4_V_read_1_reg_1367_pp0_iter1_reg;
reg   [7:0] src_buf5_3_V_read_1_reg_1372;
reg   [7:0] src_buf5_3_V_read_1_reg_1372_pp0_iter1_reg;
reg   [7:0] src_buf5_3_V_read_1_reg_1372_pp0_iter2_reg;
reg   [7:0] src_buf5_3_V_read_1_reg_1372_pp0_iter3_reg;
reg   [7:0] src_buf5_3_V_read_1_reg_1372_pp0_iter4_reg;
reg   [7:0] src_buf5_2_V_read_1_reg_1377;
reg   [7:0] src_buf5_1_V_read_1_reg_1382;
reg   [7:0] src_buf5_0_V_read_1_reg_1387;
reg   [7:0] src_buf4_3_V_read_1_reg_1392;
reg   [7:0] src_buf3_3_V_read_1_reg_1397;
reg   [7:0] src_buf3_3_V_read_1_reg_1397_pp0_iter1_reg;
reg   [7:0] src_buf3_3_V_read_1_reg_1397_pp0_iter2_reg;
reg   [7:0] src_buf3_3_V_read_1_reg_1397_pp0_iter3_reg;
reg   [7:0] src_buf3_3_V_read_1_reg_1397_pp0_iter4_reg;
reg   [7:0] src_buf2_3_V_read_1_reg_1402;
reg   [7:0] src_buf2_3_V_read_1_reg_1402_pp0_iter1_reg;
reg   [7:0] src_buf2_3_V_read_1_reg_1402_pp0_iter2_reg;
reg   [7:0] src_buf2_3_V_read_1_reg_1402_pp0_iter3_reg;
reg   [7:0] src_buf2_3_V_read_1_reg_1402_pp0_iter4_reg;
reg   [7:0] src_buf1_3_V_read_1_reg_1407;
reg   [7:0] src_buf1_3_V_read_1_reg_1407_pp0_iter1_reg;
reg   [7:0] src_buf1_3_V_read_1_reg_1407_pp0_iter2_reg;
reg   [7:0] src_buf1_3_V_read_1_reg_1407_pp0_iter3_reg;
reg   [7:0] src_buf1_3_V_read_1_reg_1407_pp0_iter4_reg;
wire   [8:0] ret_V_2_fu_452_p2;
reg   [8:0] ret_V_2_reg_1412;
reg   [8:0] ret_V_2_reg_1412_pp0_iter1_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter2_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter3_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter4_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter5_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter6_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter7_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter8_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter9_reg;
reg   [8:0] ret_V_2_reg_1412_pp0_iter10_reg;
wire   [8:0] ret_V_5_fu_466_p2;
reg   [8:0] ret_V_5_reg_1418;
reg   [8:0] ret_V_5_reg_1418_pp0_iter1_reg;
wire   [8:0] ret_V_3_fu_488_p2;
reg   [8:0] ret_V_3_reg_1424;
wire   [8:0] ret_V_8_fu_502_p2;
reg   [8:0] ret_V_8_reg_1429;
wire   [8:0] ret_V_13_fu_516_p2;
reg   [8:0] ret_V_13_reg_1434;
wire   [8:0] ret_V_19_fu_530_p2;
reg   [8:0] ret_V_19_reg_1439;
wire   [8:0] ret_V_22_fu_544_p2;
reg   [8:0] ret_V_22_reg_1444;
wire   [8:0] ret_V_26_fu_558_p2;
reg   [8:0] ret_V_26_reg_1449;
wire   [8:0] ret_V_32_fu_572_p2;
reg   [8:0] ret_V_32_reg_1454;
wire   [8:0] ret_V_35_fu_586_p2;
reg   [8:0] ret_V_35_reg_1459;
wire   [8:0] ret_V_39_fu_600_p2;
reg   [8:0] ret_V_39_reg_1464;
wire   [14:0] ret_V_1_fu_609_p2;
reg   [14:0] ret_V_1_reg_1469;
wire   [9:0] ret_V_4_fu_621_p2;
reg   [9:0] ret_V_4_reg_1474;
wire   [9:0] ret_V_10_fu_633_p2;
reg   [9:0] ret_V_10_reg_1479;
wire   [9:0] ret_V_14_fu_645_p2;
reg   [9:0] ret_V_14_reg_1484;
wire   [9:0] ret_V_20_fu_657_p2;
reg   [9:0] ret_V_20_reg_1489;
wire   [9:0] ret_V_23_fu_669_p2;
reg   [9:0] ret_V_23_reg_1494;
wire   [9:0] ret_V_27_fu_681_p2;
reg   [9:0] ret_V_27_reg_1499;
wire   [9:0] ret_V_33_fu_693_p2;
reg   [9:0] ret_V_33_reg_1504;
wire   [9:0] ret_V_36_fu_705_p2;
reg   [9:0] ret_V_36_reg_1509;
wire   [9:0] ret_V_40_fu_717_p2;
reg   [9:0] ret_V_40_reg_1514;
wire   [14:0] ret_V_6_fu_745_p2;
reg   [14:0] ret_V_6_reg_1519;
wire   [15:0] grp_fu_1218_p4;
reg   [15:0] tmp3_reg_1524;
wire   [9:0] ret_V_7_fu_757_p2;
reg   [9:0] ret_V_7_reg_1529;
reg   [9:0] ret_V_7_reg_1529_pp0_iter3_reg;
reg   [9:0] ret_V_7_reg_1529_pp0_iter4_reg;
reg   [9:0] ret_V_7_reg_1529_pp0_iter5_reg;
reg   [9:0] ret_V_7_reg_1529_pp0_iter6_reg;
reg   [9:0] ret_V_7_reg_1529_pp0_iter7_reg;
wire   [9:0] ret_V_11_fu_765_p2;
reg   [9:0] ret_V_11_reg_1535;
reg   [9:0] ret_V_11_reg_1535_pp0_iter3_reg;
reg   [9:0] ret_V_11_reg_1535_pp0_iter4_reg;
reg   [9:0] ret_V_11_reg_1535_pp0_iter5_reg;
reg   [9:0] ret_V_11_reg_1535_pp0_iter6_reg;
wire   [9:0] ret_V_15_fu_773_p2;
reg   [9:0] ret_V_15_reg_1541;
wire   [9:0] ret_V_21_fu_781_p2;
reg   [9:0] ret_V_21_reg_1546;
reg   [9:0] ret_V_21_reg_1546_pp0_iter3_reg;
reg   [9:0] ret_V_21_reg_1546_pp0_iter4_reg;
reg   [9:0] ret_V_21_reg_1546_pp0_iter5_reg;
reg   [9:0] ret_V_21_reg_1546_pp0_iter6_reg;
reg   [9:0] ret_V_21_reg_1546_pp0_iter7_reg;
wire   [9:0] ret_V_24_fu_789_p2;
reg   [9:0] ret_V_24_reg_1552;
reg   [9:0] ret_V_24_reg_1552_pp0_iter3_reg;
reg   [9:0] ret_V_24_reg_1552_pp0_iter4_reg;
reg   [9:0] ret_V_24_reg_1552_pp0_iter5_reg;
reg   [9:0] ret_V_24_reg_1552_pp0_iter6_reg;
wire   [9:0] ret_V_28_fu_797_p2;
reg   [9:0] ret_V_28_reg_1558;
wire   [9:0] ret_V_34_fu_805_p2;
reg   [9:0] ret_V_34_reg_1563;
reg   [9:0] ret_V_34_reg_1563_pp0_iter3_reg;
reg   [9:0] ret_V_34_reg_1563_pp0_iter4_reg;
reg   [9:0] ret_V_34_reg_1563_pp0_iter5_reg;
reg   [9:0] ret_V_34_reg_1563_pp0_iter6_reg;
reg   [9:0] ret_V_34_reg_1563_pp0_iter7_reg;
wire   [9:0] ret_V_37_fu_813_p2;
reg   [9:0] ret_V_37_reg_1569;
reg   [9:0] ret_V_37_reg_1569_pp0_iter3_reg;
reg   [9:0] ret_V_37_reg_1569_pp0_iter4_reg;
reg   [9:0] ret_V_37_reg_1569_pp0_iter5_reg;
reg   [9:0] ret_V_37_reg_1569_pp0_iter6_reg;
wire   [9:0] ret_V_41_fu_821_p2;
reg   [9:0] ret_V_41_reg_1575;
(* use_dsp48 = "no" *) wire   [15:0] tmp2_fu_829_p2;
reg   [15:0] tmp2_reg_1580;
reg   [15:0] tmp2_reg_1580_pp0_iter4_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter5_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter6_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter7_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter8_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter9_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter10_reg;
reg   [15:0] tmp2_reg_1580_pp0_iter11_reg;
wire   [16:0] grp_fu_1228_p2;
reg   [16:0] ret_V_16_reg_1600;
wire   [16:0] grp_fu_1234_p2;
reg   [16:0] ret_V_29_reg_1605;
wire   [16:0] grp_fu_1240_p2;
reg   [16:0] ret_V_42_reg_1610;
wire   [15:0] ret_V_12_fu_883_p2;
reg   [15:0] ret_V_12_reg_1615;
wire   [16:0] grp_fu_1246_p4;
reg   [16:0] tmp8_reg_1620;
wire   [15:0] ret_V_25_fu_911_p2;
reg   [15:0] ret_V_25_reg_1625;
wire   [16:0] grp_fu_1255_p4;
reg   [16:0] tmp4_reg_1630;
wire   [15:0] ret_V_38_fu_939_p2;
reg   [15:0] ret_V_38_reg_1635;
wire   [16:0] grp_fu_1264_p4;
reg   [16:0] tmp10_reg_1640;
wire   [14:0] tmp6_fu_970_p2;
reg   [14:0] tmp6_reg_1645;
(* use_dsp48 = "no" *) wire   [16:0] tmp7_fu_976_p2;
reg   [16:0] tmp7_reg_1650;
wire   [14:0] tmp_fu_1006_p2;
reg   [14:0] tmp_reg_1655;
(* use_dsp48 = "no" *) wire   [16:0] tmp5_fu_1012_p2;
reg   [16:0] tmp5_reg_1660;
wire   [14:0] tmp9_fu_1042_p2;
reg   [14:0] tmp9_reg_1665;
(* use_dsp48 = "no" *) wire   [16:0] tmp11_fu_1048_p2;
reg   [16:0] tmp11_reg_1670;
wire   [16:0] sum_fu_1056_p2;
reg   [16:0] sum_reg_1675;
reg   [16:0] sum_reg_1675_pp0_iter10_reg;
reg   [16:0] sum_reg_1675_pp0_iter11_reg;
reg   [16:0] sum_reg_1675_pp0_iter12_reg;
reg   [16:0] sum_reg_1675_pp0_iter13_reg;
reg   [16:0] sum_reg_1675_pp0_iter14_reg;
wire   [16:0] sum1_fu_1064_p2;
reg   [16:0] sum1_reg_1681;
reg   [16:0] sum1_reg_1681_pp0_iter10_reg;
reg   [16:0] sum1_reg_1681_pp0_iter11_reg;
reg   [16:0] sum1_reg_1681_pp0_iter12_reg;
reg   [16:0] sum1_reg_1681_pp0_iter13_reg;
reg   [16:0] sum1_reg_1681_pp0_iter14_reg;
wire   [16:0] sum2_fu_1072_p2;
reg   [16:0] sum2_reg_1687;
wire   [13:0] tmp1_fu_1102_p2;
reg   [13:0] tmp1_reg_1697;
wire   [23:0] grp_fu_1273_p2;
reg   [23:0] tmp_s_reg_1702;
wire   [18:0] tmp12_fu_1133_p2;
reg   [18:0] tmp12_reg_1707;
wire   [23:0] grp_fu_1279_p4;
reg   [23:0] tmp14_reg_1712;
wire   [22:0] tmp13_fu_1164_p2;
reg   [22:0] tmp13_reg_1717;
(* use_dsp48 = "no" *) wire   [23:0] tmp15_fu_1170_p2;
reg   [23:0] tmp15_reg_1722;
reg   [8:0] val_cast_reg_1727;
reg   [7:0] value_reg_1732;
reg   [7:0] value_reg_1732_pp0_iter17_reg;
wire   [0:0] tmp_4_fu_1207_p2;
reg   [0:0] tmp_4_reg_1737;
wire    ap_block_pp0_stage0;
wire   [8:0] rhs_V_fu_448_p1;
wire   [8:0] lhs_V_fu_444_p1;
wire   [8:0] rhs_V_1_fu_462_p1;
wire   [8:0] lhs_V_1_fu_458_p1;
wire   [8:0] rhs_V_3_fu_484_p1;
wire   [8:0] lhs_V_6_fu_480_p1;
wire   [8:0] rhs_V_6_fu_498_p1;
wire   [8:0] lhs_V_9_fu_494_p1;
wire   [8:0] rhs_V_9_fu_512_p1;
wire   [8:0] lhs_V_2_fu_508_p1;
wire   [8:0] rhs_V_8_fu_526_p1;
wire   [8:0] lhs_V_8_fu_522_p1;
wire   [8:0] rhs_V_11_fu_540_p1;
wire   [8:0] lhs_V_11_fu_536_p1;
wire   [8:0] rhs_V_13_fu_554_p1;
wire   [8:0] lhs_V_13_fu_550_p1;
wire   [8:0] rhs_V_16_fu_568_p1;
wire   [8:0] lhs_V_16_fu_564_p1;
wire   [8:0] rhs_V_18_fu_582_p1;
wire   [8:0] lhs_V_18_fu_578_p1;
wire   [8:0] rhs_V_20_fu_596_p1;
wire   [8:0] lhs_V_20_fu_592_p1;
wire   [7:0] ret_V_1_fu_609_p0;
wire   [9:0] rhs_V_4_fu_618_p1;
wire   [9:0] lhs_V_7_fu_615_p1;
wire   [9:0] rhs_V_7_fu_630_p1;
wire   [9:0] lhs_V_s_fu_627_p1;
wire   [9:0] rhs_V_s_fu_642_p1;
wire   [9:0] lhs_V_4_fu_639_p1;
wire   [9:0] rhs_V_10_fu_654_p1;
wire   [9:0] lhs_V_10_fu_651_p1;
wire   [9:0] rhs_V_12_fu_666_p1;
wire   [9:0] lhs_V_12_fu_663_p1;
wire   [9:0] rhs_V_14_fu_678_p1;
wire   [9:0] lhs_V_14_fu_675_p1;
wire   [9:0] rhs_V_17_fu_690_p1;
wire   [9:0] lhs_V_17_fu_687_p1;
wire   [9:0] rhs_V_19_fu_702_p1;
wire   [9:0] lhs_V_19_fu_699_p1;
wire   [9:0] rhs_V_21_fu_714_p1;
wire   [9:0] lhs_V_21_fu_711_p1;
wire   [13:0] p_shl17_fu_723_p3;
wire   [9:0] p_shl18_fu_734_p3;
wire   [14:0] p_shl18_cast_fu_741_p1;
wire   [14:0] p_shl17_cast_fu_730_p1;
wire   [9:0] rhs_V_5_cast_fu_754_p1;
wire   [9:0] rhs_V_8_cast_fu_762_p1;
wire   [9:0] rhs_V_10_cast_fu_770_p1;
wire   [9:0] rhs_V_14_cast_fu_778_p1;
wire   [9:0] rhs_V_17_cast_fu_786_p1;
wire   [9:0] rhs_V_20_cast_fu_794_p1;
wire   [9:0] rhs_V_24_cast_fu_802_p1;
wire   [9:0] rhs_V_27_cast_fu_810_p1;
wire   [9:0] rhs_V_30_cast_fu_818_p1;
wire   [15:0] tmp_6_cast_fu_826_p1;
wire   [14:0] p_shl13_fu_861_p3;
wire   [10:0] p_shl14_fu_872_p3;
wire   [15:0] p_shl14_cast_fu_879_p1;
wire   [15:0] p_shl13_cast_fu_868_p1;
wire   [14:0] p_shl9_fu_889_p3;
wire   [10:0] p_shl10_fu_900_p3;
wire   [15:0] p_shl10_cast_fu_907_p1;
wire   [15:0] p_shl9_cast_fu_896_p1;
wire   [14:0] p_shl5_fu_917_p3;
wire   [10:0] p_shl6_fu_928_p3;
wire   [15:0] p_shl6_cast_fu_935_p1;
wire   [15:0] p_shl5_cast_fu_924_p1;
wire   [13:0] p_shl15_fu_945_p3;
wire   [10:0] p_shl16_fu_956_p3;
wire   [14:0] p_shl15_cast_fu_952_p1;
wire   [14:0] p_shl16_cast_fu_963_p1;
wire   [16:0] tmp_5_cast_fu_967_p1;
wire   [13:0] p_shl11_fu_981_p3;
wire   [10:0] p_shl12_fu_992_p3;
wire   [14:0] p_shl11_cast_fu_988_p1;
wire   [14:0] p_shl12_cast_fu_999_p1;
wire   [16:0] tmp_12_cast_fu_1003_p1;
wire   [13:0] p_shl7_fu_1017_p3;
wire   [10:0] p_shl8_fu_1028_p3;
wire   [14:0] p_shl8_cast_fu_1035_p1;
wire   [14:0] p_shl7_cast_fu_1024_p1;
wire   [16:0] tmp_18_cast_fu_1039_p1;
wire   [16:0] tmp6_cast_fu_1053_p1;
wire   [16:0] tmp11_cast_fu_1061_p1;
wire   [16:0] tmp14_cast_fu_1069_p1;
wire   [12:0] p_shl1_fu_1080_p3;
wire   [9:0] p_shl19_fu_1091_p3;
wire   [13:0] p_shl19_cast_fu_1098_p1;
wire   [13:0] p_shl1_cast_fu_1087_p1;
wire   [17:0] p_shl4_fu_1111_p3;
wire   [17:0] p_shl2_fu_1122_p3;
wire   [18:0] p_shl4_cast_fu_1118_p1;
wire   [18:0] p_shl2_cast_fu_1129_p1;
wire   [20:0] p_shl3_fu_1139_p3;
wire   [21:0] p_shl_fu_1150_p3;
wire   [22:0] p_shl_cast_fu_1157_p1;
wire   [22:0] tmp18_cast_fu_1161_p1;
wire   [23:0] p_shl3_cast_fu_1146_p1;
wire   [24:0] tmp17_cast_fu_1175_p1;
wire   [24:0] tmp19_cast_fu_1178_p1;
wire   [24:0] tmp_2_fu_1181_p2;
wire   [7:0] grp_fu_1218_p0;
wire   [7:0] grp_fu_1218_p1;
wire   [6:0] grp_fu_1218_p2;
wire   [14:0] grp_fu_1218_p3;
wire   [9:0] grp_fu_1228_p0;
wire   [6:0] grp_fu_1228_p1;
wire   [9:0] grp_fu_1234_p0;
wire   [6:0] grp_fu_1234_p1;
wire   [9:0] grp_fu_1240_p0;
wire   [6:0] grp_fu_1240_p1;
wire   [7:0] grp_fu_1246_p0;
wire   [7:0] grp_fu_1246_p1;
wire   [6:0] grp_fu_1246_p2;
wire   [7:0] grp_fu_1255_p0;
wire   [7:0] grp_fu_1255_p1;
wire   [6:0] grp_fu_1255_p2;
wire   [7:0] grp_fu_1264_p0;
wire   [7:0] grp_fu_1264_p1;
wire   [6:0] grp_fu_1264_p2;
wire   [16:0] grp_fu_1273_p0;
wire   [6:0] grp_fu_1273_p1;
wire   [13:0] grp_fu_1279_p0;
wire   [6:0] grp_fu_1279_p2;
wire   [7:0] value_2_fu_1212_p3;
reg    grp_fu_1218_ce;
reg    grp_fu_1228_ce;
reg    grp_fu_1234_ce;
reg    grp_fu_1240_ce;
reg    grp_fu_1246_ce;
reg    grp_fu_1255_ce;
reg    grp_fu_1264_ce;
reg    grp_fu_1273_ce;
reg    grp_fu_1279_ce;
reg    ap_ce_reg;
reg   [7:0] src_buf1_0_V_read_int_reg;
reg   [7:0] src_buf1_1_V_read_int_reg;
reg   [7:0] src_buf1_2_V_read_int_reg;
reg   [7:0] src_buf1_3_V_read_int_reg;
reg   [7:0] src_buf1_4_V_read_int_reg;
reg   [7:0] src_buf1_5_V_read_int_reg;
reg   [7:0] src_buf1_6_V_read_int_reg;
reg   [7:0] src_buf2_0_V_read_int_reg;
reg   [7:0] src_buf2_1_V_read_int_reg;
reg   [7:0] src_buf2_2_V_read_int_reg;
reg   [7:0] src_buf2_3_V_read_int_reg;
reg   [7:0] src_buf2_4_V_read_int_reg;
reg   [7:0] src_buf2_5_V_read_int_reg;
reg   [7:0] src_buf2_6_V_read_int_reg;
reg   [7:0] src_buf3_0_V_read_int_reg;
reg   [7:0] src_buf3_1_V_read_int_reg;
reg   [7:0] src_buf3_2_V_read_int_reg;
reg   [7:0] src_buf3_3_V_read_int_reg;
reg   [7:0] src_buf3_4_V_read_int_reg;
reg   [7:0] src_buf3_5_V_read_int_reg;
reg   [7:0] src_buf3_6_V_read_int_reg;
reg   [7:0] src_buf4_0_V_read_int_reg;
reg   [7:0] src_buf4_1_V_read_int_reg;
reg   [7:0] src_buf4_2_V_read_int_reg;
reg   [7:0] src_buf4_3_V_read_int_reg;
reg   [7:0] src_buf4_4_V_read_int_reg;
reg   [7:0] src_buf4_5_V_read_int_reg;
reg   [7:0] src_buf4_6_V_read_int_reg;
reg   [7:0] src_buf5_0_V_read_int_reg;
reg   [7:0] src_buf5_1_V_read_int_reg;
reg   [7:0] src_buf5_2_V_read_int_reg;
reg   [7:0] src_buf5_3_V_read_int_reg;
reg   [7:0] src_buf5_4_V_read_int_reg;
reg   [7:0] src_buf5_5_V_read_int_reg;
reg   [7:0] src_buf5_6_V_read_int_reg;
reg   [7:0] src_buf6_0_V_read_int_reg;
reg   [7:0] src_buf6_1_V_read_int_reg;
reg   [7:0] src_buf6_2_V_read_int_reg;
reg   [7:0] src_buf6_3_V_read_int_reg;
reg   [7:0] src_buf6_4_V_read_int_reg;
reg   [7:0] src_buf6_5_V_read_int_reg;
reg   [7:0] src_buf6_6_V_read_int_reg;
reg   [7:0] src_buf7_0_V_read_int_reg;
reg   [7:0] src_buf7_1_V_read_int_reg;
reg   [7:0] src_buf7_2_V_read_int_reg;
reg   [7:0] src_buf7_3_V_read_int_reg;
reg   [7:0] src_buf7_4_V_read_int_reg;
reg   [7:0] src_buf7_5_V_read_int_reg;
reg   [7:0] src_buf7_6_V_read_int_reg;
reg   [7:0] ap_return_int_reg;
wire   [8:0] grp_fu_1218_p00;
wire   [8:0] grp_fu_1218_p10;
wire   [15:0] grp_fu_1218_p30;
wire   [16:0] grp_fu_1228_p00;
wire   [16:0] grp_fu_1234_p00;
wire   [16:0] grp_fu_1240_p00;
wire   [8:0] grp_fu_1246_p00;
wire   [8:0] grp_fu_1246_p10;
wire   [8:0] grp_fu_1255_p00;
wire   [8:0] grp_fu_1255_p10;
wire   [8:0] grp_fu_1264_p00;
wire   [8:0] grp_fu_1264_p10;
wire   [23:0] grp_fu_1273_p00;
wire   [15:0] grp_fu_1279_p00;
wire   [14:0] ret_V_1_fu_609_p00;

gaussian_filter_abkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
gaussian_filter_abkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1218_p0),
    .din1(grp_fu_1218_p1),
    .din2(grp_fu_1218_p2),
    .din3(grp_fu_1218_p3),
    .ce(grp_fu_1218_ce),
    .dout(grp_fu_1218_p4)
);

gaussian_filter_acud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
gaussian_filter_acud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1228_p0),
    .din1(grp_fu_1228_p1),
    .ce(grp_fu_1228_ce),
    .dout(grp_fu_1228_p2)
);

gaussian_filter_acud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
gaussian_filter_acud_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1234_p0),
    .din1(grp_fu_1234_p1),
    .ce(grp_fu_1234_ce),
    .dout(grp_fu_1234_p2)
);

gaussian_filter_acud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 17 ))
gaussian_filter_acud_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1240_p0),
    .din1(grp_fu_1240_p1),
    .ce(grp_fu_1240_ce),
    .dout(grp_fu_1240_p2)
);

gaussian_filter_adEe #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
gaussian_filter_adEe_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1246_p0),
    .din1(grp_fu_1246_p1),
    .din2(grp_fu_1246_p2),
    .din3(ret_V_16_reg_1600),
    .ce(grp_fu_1246_ce),
    .dout(grp_fu_1246_p4)
);

gaussian_filter_adEe #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
gaussian_filter_adEe_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1255_p0),
    .din1(grp_fu_1255_p1),
    .din2(grp_fu_1255_p2),
    .din3(ret_V_29_reg_1605),
    .ce(grp_fu_1255_ce),
    .dout(grp_fu_1255_p4)
);

gaussian_filter_adEe #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
gaussian_filter_adEe_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1264_p0),
    .din1(grp_fu_1264_p1),
    .din2(grp_fu_1264_p2),
    .din3(ret_V_42_reg_1610),
    .ce(grp_fu_1264_ce),
    .dout(grp_fu_1264_p4)
);

gaussian_filter_aeOg #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 24 ))
gaussian_filter_aeOg_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1273_p0),
    .din1(grp_fu_1273_p1),
    .ce(grp_fu_1273_ce),
    .dout(grp_fu_1273_p2)
);

gaussian_filter_afYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_filter_afYi_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1279_p0),
    .din1(tmp2_reg_1580_pp0_iter11_reg),
    .din2(grp_fu_1279_p2),
    .din3(tmp_s_reg_1702),
    .ce(grp_fu_1279_ce),
    .dout(grp_fu_1279_p4)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= value_2_fu_1212_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ret_V_10_reg_1479 <= ret_V_10_fu_633_p2;
        ret_V_11_reg_1535 <= ret_V_11_fu_765_p2;
        ret_V_11_reg_1535_pp0_iter3_reg <= ret_V_11_reg_1535;
        ret_V_11_reg_1535_pp0_iter4_reg <= ret_V_11_reg_1535_pp0_iter3_reg;
        ret_V_11_reg_1535_pp0_iter5_reg <= ret_V_11_reg_1535_pp0_iter4_reg;
        ret_V_11_reg_1535_pp0_iter6_reg <= ret_V_11_reg_1535_pp0_iter5_reg;
        ret_V_12_reg_1615[15 : 1] <= ret_V_12_fu_883_p2[15 : 1];
        ret_V_13_reg_1434 <= ret_V_13_fu_516_p2;
        ret_V_14_reg_1484 <= ret_V_14_fu_645_p2;
        ret_V_15_reg_1541 <= ret_V_15_fu_773_p2;
        ret_V_16_reg_1600 <= grp_fu_1228_p2;
        ret_V_19_reg_1439 <= ret_V_19_fu_530_p2;
        ret_V_1_reg_1469 <= ret_V_1_fu_609_p2;
        ret_V_20_reg_1489 <= ret_V_20_fu_657_p2;
        ret_V_21_reg_1546 <= ret_V_21_fu_781_p2;
        ret_V_21_reg_1546_pp0_iter3_reg <= ret_V_21_reg_1546;
        ret_V_21_reg_1546_pp0_iter4_reg <= ret_V_21_reg_1546_pp0_iter3_reg;
        ret_V_21_reg_1546_pp0_iter5_reg <= ret_V_21_reg_1546_pp0_iter4_reg;
        ret_V_21_reg_1546_pp0_iter6_reg <= ret_V_21_reg_1546_pp0_iter5_reg;
        ret_V_21_reg_1546_pp0_iter7_reg <= ret_V_21_reg_1546_pp0_iter6_reg;
        ret_V_22_reg_1444 <= ret_V_22_fu_544_p2;
        ret_V_23_reg_1494 <= ret_V_23_fu_669_p2;
        ret_V_24_reg_1552 <= ret_V_24_fu_789_p2;
        ret_V_24_reg_1552_pp0_iter3_reg <= ret_V_24_reg_1552;
        ret_V_24_reg_1552_pp0_iter4_reg <= ret_V_24_reg_1552_pp0_iter3_reg;
        ret_V_24_reg_1552_pp0_iter5_reg <= ret_V_24_reg_1552_pp0_iter4_reg;
        ret_V_24_reg_1552_pp0_iter6_reg <= ret_V_24_reg_1552_pp0_iter5_reg;
        ret_V_25_reg_1625[15 : 1] <= ret_V_25_fu_911_p2[15 : 1];
        ret_V_26_reg_1449 <= ret_V_26_fu_558_p2;
        ret_V_27_reg_1499 <= ret_V_27_fu_681_p2;
        ret_V_28_reg_1558 <= ret_V_28_fu_797_p2;
        ret_V_29_reg_1605 <= grp_fu_1234_p2;
        ret_V_2_reg_1412 <= ret_V_2_fu_452_p2;
        ret_V_2_reg_1412_pp0_iter10_reg <= ret_V_2_reg_1412_pp0_iter9_reg;
        ret_V_2_reg_1412_pp0_iter1_reg <= ret_V_2_reg_1412;
        ret_V_2_reg_1412_pp0_iter2_reg <= ret_V_2_reg_1412_pp0_iter1_reg;
        ret_V_2_reg_1412_pp0_iter3_reg <= ret_V_2_reg_1412_pp0_iter2_reg;
        ret_V_2_reg_1412_pp0_iter4_reg <= ret_V_2_reg_1412_pp0_iter3_reg;
        ret_V_2_reg_1412_pp0_iter5_reg <= ret_V_2_reg_1412_pp0_iter4_reg;
        ret_V_2_reg_1412_pp0_iter6_reg <= ret_V_2_reg_1412_pp0_iter5_reg;
        ret_V_2_reg_1412_pp0_iter7_reg <= ret_V_2_reg_1412_pp0_iter6_reg;
        ret_V_2_reg_1412_pp0_iter8_reg <= ret_V_2_reg_1412_pp0_iter7_reg;
        ret_V_2_reg_1412_pp0_iter9_reg <= ret_V_2_reg_1412_pp0_iter8_reg;
        ret_V_32_reg_1454 <= ret_V_32_fu_572_p2;
        ret_V_33_reg_1504 <= ret_V_33_fu_693_p2;
        ret_V_34_reg_1563 <= ret_V_34_fu_805_p2;
        ret_V_34_reg_1563_pp0_iter3_reg <= ret_V_34_reg_1563;
        ret_V_34_reg_1563_pp0_iter4_reg <= ret_V_34_reg_1563_pp0_iter3_reg;
        ret_V_34_reg_1563_pp0_iter5_reg <= ret_V_34_reg_1563_pp0_iter4_reg;
        ret_V_34_reg_1563_pp0_iter6_reg <= ret_V_34_reg_1563_pp0_iter5_reg;
        ret_V_34_reg_1563_pp0_iter7_reg <= ret_V_34_reg_1563_pp0_iter6_reg;
        ret_V_35_reg_1459 <= ret_V_35_fu_586_p2;
        ret_V_36_reg_1509 <= ret_V_36_fu_705_p2;
        ret_V_37_reg_1569 <= ret_V_37_fu_813_p2;
        ret_V_37_reg_1569_pp0_iter3_reg <= ret_V_37_reg_1569;
        ret_V_37_reg_1569_pp0_iter4_reg <= ret_V_37_reg_1569_pp0_iter3_reg;
        ret_V_37_reg_1569_pp0_iter5_reg <= ret_V_37_reg_1569_pp0_iter4_reg;
        ret_V_37_reg_1569_pp0_iter6_reg <= ret_V_37_reg_1569_pp0_iter5_reg;
        ret_V_38_reg_1635[15 : 1] <= ret_V_38_fu_939_p2[15 : 1];
        ret_V_39_reg_1464 <= ret_V_39_fu_600_p2;
        ret_V_3_reg_1424 <= ret_V_3_fu_488_p2;
        ret_V_40_reg_1514 <= ret_V_40_fu_717_p2;
        ret_V_41_reg_1575 <= ret_V_41_fu_821_p2;
        ret_V_42_reg_1610 <= grp_fu_1240_p2;
        ret_V_4_reg_1474 <= ret_V_4_fu_621_p2;
        ret_V_5_reg_1418 <= ret_V_5_fu_466_p2;
        ret_V_5_reg_1418_pp0_iter1_reg <= ret_V_5_reg_1418;
        ret_V_6_reg_1519[14 : 1] <= ret_V_6_fu_745_p2[14 : 1];
        ret_V_7_reg_1529 <= ret_V_7_fu_757_p2;
        ret_V_7_reg_1529_pp0_iter3_reg <= ret_V_7_reg_1529;
        ret_V_7_reg_1529_pp0_iter4_reg <= ret_V_7_reg_1529_pp0_iter3_reg;
        ret_V_7_reg_1529_pp0_iter5_reg <= ret_V_7_reg_1529_pp0_iter4_reg;
        ret_V_7_reg_1529_pp0_iter6_reg <= ret_V_7_reg_1529_pp0_iter5_reg;
        ret_V_7_reg_1529_pp0_iter7_reg <= ret_V_7_reg_1529_pp0_iter6_reg;
        ret_V_8_reg_1429 <= ret_V_8_fu_502_p2;
        src_buf1_3_V_read_1_reg_1407 <= src_buf1_3_V_read_int_reg;
        src_buf1_3_V_read_1_reg_1407_pp0_iter1_reg <= src_buf1_3_V_read_1_reg_1407;
        src_buf1_3_V_read_1_reg_1407_pp0_iter2_reg <= src_buf1_3_V_read_1_reg_1407_pp0_iter1_reg;
        src_buf1_3_V_read_1_reg_1407_pp0_iter3_reg <= src_buf1_3_V_read_1_reg_1407_pp0_iter2_reg;
        src_buf1_3_V_read_1_reg_1407_pp0_iter4_reg <= src_buf1_3_V_read_1_reg_1407_pp0_iter3_reg;
        src_buf2_3_V_read_1_reg_1402 <= src_buf2_3_V_read_int_reg;
        src_buf2_3_V_read_1_reg_1402_pp0_iter1_reg <= src_buf2_3_V_read_1_reg_1402;
        src_buf2_3_V_read_1_reg_1402_pp0_iter2_reg <= src_buf2_3_V_read_1_reg_1402_pp0_iter1_reg;
        src_buf2_3_V_read_1_reg_1402_pp0_iter3_reg <= src_buf2_3_V_read_1_reg_1402_pp0_iter2_reg;
        src_buf2_3_V_read_1_reg_1402_pp0_iter4_reg <= src_buf2_3_V_read_1_reg_1402_pp0_iter3_reg;
        src_buf3_3_V_read_1_reg_1397 <= src_buf3_3_V_read_int_reg;
        src_buf3_3_V_read_1_reg_1397_pp0_iter1_reg <= src_buf3_3_V_read_1_reg_1397;
        src_buf3_3_V_read_1_reg_1397_pp0_iter2_reg <= src_buf3_3_V_read_1_reg_1397_pp0_iter1_reg;
        src_buf3_3_V_read_1_reg_1397_pp0_iter3_reg <= src_buf3_3_V_read_1_reg_1397_pp0_iter2_reg;
        src_buf3_3_V_read_1_reg_1397_pp0_iter4_reg <= src_buf3_3_V_read_1_reg_1397_pp0_iter3_reg;
        src_buf4_3_V_read_1_reg_1392 <= src_buf4_3_V_read_int_reg;
        src_buf5_0_V_read_1_reg_1387 <= src_buf5_0_V_read_int_reg;
        src_buf5_1_V_read_1_reg_1382 <= src_buf5_1_V_read_int_reg;
        src_buf5_2_V_read_1_reg_1377 <= src_buf5_2_V_read_int_reg;
        src_buf5_3_V_read_1_reg_1372 <= src_buf5_3_V_read_int_reg;
        src_buf5_3_V_read_1_reg_1372_pp0_iter1_reg <= src_buf5_3_V_read_1_reg_1372;
        src_buf5_3_V_read_1_reg_1372_pp0_iter2_reg <= src_buf5_3_V_read_1_reg_1372_pp0_iter1_reg;
        src_buf5_3_V_read_1_reg_1372_pp0_iter3_reg <= src_buf5_3_V_read_1_reg_1372_pp0_iter2_reg;
        src_buf5_3_V_read_1_reg_1372_pp0_iter4_reg <= src_buf5_3_V_read_1_reg_1372_pp0_iter3_reg;
        src_buf5_4_V_read_1_reg_1367 <= src_buf5_4_V_read_int_reg;
        src_buf5_4_V_read_1_reg_1367_pp0_iter1_reg <= src_buf5_4_V_read_1_reg_1367;
        src_buf5_5_V_read_1_reg_1362 <= src_buf5_5_V_read_int_reg;
        src_buf5_5_V_read_1_reg_1362_pp0_iter1_reg <= src_buf5_5_V_read_1_reg_1362;
        src_buf5_6_V_read_1_reg_1357 <= src_buf5_6_V_read_int_reg;
        src_buf5_6_V_read_1_reg_1357_pp0_iter1_reg <= src_buf5_6_V_read_1_reg_1357;
        src_buf6_0_V_read_1_reg_1352 <= src_buf6_0_V_read_int_reg;
        src_buf6_1_V_read_1_reg_1347 <= src_buf6_1_V_read_int_reg;
        src_buf6_2_V_read_1_reg_1342 <= src_buf6_2_V_read_int_reg;
        src_buf6_3_V_read_1_reg_1337 <= src_buf6_3_V_read_int_reg;
        src_buf6_3_V_read_1_reg_1337_pp0_iter1_reg <= src_buf6_3_V_read_1_reg_1337;
        src_buf6_3_V_read_1_reg_1337_pp0_iter2_reg <= src_buf6_3_V_read_1_reg_1337_pp0_iter1_reg;
        src_buf6_3_V_read_1_reg_1337_pp0_iter3_reg <= src_buf6_3_V_read_1_reg_1337_pp0_iter2_reg;
        src_buf6_3_V_read_1_reg_1337_pp0_iter4_reg <= src_buf6_3_V_read_1_reg_1337_pp0_iter3_reg;
        src_buf6_4_V_read_1_reg_1332 <= src_buf6_4_V_read_int_reg;
        src_buf6_4_V_read_1_reg_1332_pp0_iter1_reg <= src_buf6_4_V_read_1_reg_1332;
        src_buf6_5_V_read_1_reg_1327 <= src_buf6_5_V_read_int_reg;
        src_buf6_5_V_read_1_reg_1327_pp0_iter1_reg <= src_buf6_5_V_read_1_reg_1327;
        src_buf6_6_V_read_1_reg_1322 <= src_buf6_6_V_read_int_reg;
        src_buf6_6_V_read_1_reg_1322_pp0_iter1_reg <= src_buf6_6_V_read_1_reg_1322;
        src_buf7_0_V_read_1_reg_1317 <= src_buf7_0_V_read_int_reg;
        src_buf7_1_V_read_1_reg_1312 <= src_buf7_1_V_read_int_reg;
        src_buf7_2_V_read_1_reg_1307 <= src_buf7_2_V_read_int_reg;
        src_buf7_3_V_read_1_reg_1302 <= src_buf7_3_V_read_int_reg;
        src_buf7_3_V_read_1_reg_1302_pp0_iter1_reg <= src_buf7_3_V_read_1_reg_1302;
        src_buf7_3_V_read_1_reg_1302_pp0_iter2_reg <= src_buf7_3_V_read_1_reg_1302_pp0_iter1_reg;
        src_buf7_3_V_read_1_reg_1302_pp0_iter3_reg <= src_buf7_3_V_read_1_reg_1302_pp0_iter2_reg;
        src_buf7_3_V_read_1_reg_1302_pp0_iter4_reg <= src_buf7_3_V_read_1_reg_1302_pp0_iter3_reg;
        src_buf7_4_V_read_1_reg_1297 <= src_buf7_4_V_read_int_reg;
        src_buf7_4_V_read_1_reg_1297_pp0_iter1_reg <= src_buf7_4_V_read_1_reg_1297;
        src_buf7_5_V_read_1_reg_1292 <= src_buf7_5_V_read_int_reg;
        src_buf7_5_V_read_1_reg_1292_pp0_iter1_reg <= src_buf7_5_V_read_1_reg_1292;
        src_buf7_6_V_read_1_reg_1287 <= src_buf7_6_V_read_int_reg;
        src_buf7_6_V_read_1_reg_1287_pp0_iter1_reg <= src_buf7_6_V_read_1_reg_1287;
        sum1_reg_1681 <= sum1_fu_1064_p2;
        sum1_reg_1681_pp0_iter10_reg <= sum1_reg_1681;
        sum1_reg_1681_pp0_iter11_reg <= sum1_reg_1681_pp0_iter10_reg;
        sum1_reg_1681_pp0_iter12_reg <= sum1_reg_1681_pp0_iter11_reg;
        sum1_reg_1681_pp0_iter13_reg <= sum1_reg_1681_pp0_iter12_reg;
        sum1_reg_1681_pp0_iter14_reg <= sum1_reg_1681_pp0_iter13_reg;
        sum2_reg_1687 <= sum2_fu_1072_p2;
        sum_reg_1675 <= sum_fu_1056_p2;
        sum_reg_1675_pp0_iter10_reg <= sum_reg_1675;
        sum_reg_1675_pp0_iter11_reg <= sum_reg_1675_pp0_iter10_reg;
        sum_reg_1675_pp0_iter12_reg <= sum_reg_1675_pp0_iter11_reg;
        sum_reg_1675_pp0_iter13_reg <= sum_reg_1675_pp0_iter12_reg;
        sum_reg_1675_pp0_iter14_reg <= sum_reg_1675_pp0_iter13_reg;
        tmp10_reg_1640 <= grp_fu_1264_p4;
        tmp11_reg_1670 <= tmp11_fu_1048_p2;
        tmp12_reg_1707[18 : 1] <= tmp12_fu_1133_p2[18 : 1];
        tmp13_reg_1717[22 : 1] <= tmp13_fu_1164_p2[22 : 1];
        tmp14_reg_1712 <= grp_fu_1279_p4;
        tmp15_reg_1722 <= tmp15_fu_1170_p2;
        tmp1_reg_1697[13 : 1] <= tmp1_fu_1102_p2[13 : 1];
        tmp2_reg_1580 <= tmp2_fu_829_p2;
        tmp2_reg_1580_pp0_iter10_reg <= tmp2_reg_1580_pp0_iter9_reg;
        tmp2_reg_1580_pp0_iter11_reg <= tmp2_reg_1580_pp0_iter10_reg;
        tmp2_reg_1580_pp0_iter4_reg <= tmp2_reg_1580;
        tmp2_reg_1580_pp0_iter5_reg <= tmp2_reg_1580_pp0_iter4_reg;
        tmp2_reg_1580_pp0_iter6_reg <= tmp2_reg_1580_pp0_iter5_reg;
        tmp2_reg_1580_pp0_iter7_reg <= tmp2_reg_1580_pp0_iter6_reg;
        tmp2_reg_1580_pp0_iter8_reg <= tmp2_reg_1580_pp0_iter7_reg;
        tmp2_reg_1580_pp0_iter9_reg <= tmp2_reg_1580_pp0_iter8_reg;
        tmp3_reg_1524 <= grp_fu_1218_p4;
        tmp4_reg_1630 <= grp_fu_1255_p4;
        tmp5_reg_1660 <= tmp5_fu_1012_p2;
        tmp6_reg_1645[14 : 1] <= tmp6_fu_970_p2[14 : 1];
        tmp7_reg_1650 <= tmp7_fu_976_p2;
        tmp8_reg_1620 <= grp_fu_1246_p4;
        tmp9_reg_1665[14 : 1] <= tmp9_fu_1042_p2[14 : 1];
        tmp_4_reg_1737 <= tmp_4_fu_1207_p2;
        tmp_reg_1655[14 : 1] <= tmp_fu_1006_p2[14 : 1];
        tmp_s_reg_1702 <= grp_fu_1273_p2;
        val_cast_reg_1727 <= {{tmp_2_fu_1181_p2[24:16]}};
        value_reg_1732 <= {{tmp_2_fu_1181_p2[23:16]}};
        value_reg_1732_pp0_iter17_reg <= value_reg_1732;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        src_buf1_0_V_read_int_reg <= src_buf1_0_V_read;
        src_buf1_1_V_read_int_reg <= src_buf1_1_V_read;
        src_buf1_2_V_read_int_reg <= src_buf1_2_V_read;
        src_buf1_3_V_read_int_reg <= src_buf1_3_V_read;
        src_buf1_4_V_read_int_reg <= src_buf1_4_V_read;
        src_buf1_5_V_read_int_reg <= src_buf1_5_V_read;
        src_buf1_6_V_read_int_reg <= src_buf1_6_V_read;
        src_buf2_0_V_read_int_reg <= src_buf2_0_V_read;
        src_buf2_1_V_read_int_reg <= src_buf2_1_V_read;
        src_buf2_2_V_read_int_reg <= src_buf2_2_V_read;
        src_buf2_3_V_read_int_reg <= src_buf2_3_V_read;
        src_buf2_4_V_read_int_reg <= src_buf2_4_V_read;
        src_buf2_5_V_read_int_reg <= src_buf2_5_V_read;
        src_buf2_6_V_read_int_reg <= src_buf2_6_V_read;
        src_buf3_0_V_read_int_reg <= src_buf3_0_V_read;
        src_buf3_1_V_read_int_reg <= src_buf3_1_V_read;
        src_buf3_2_V_read_int_reg <= src_buf3_2_V_read;
        src_buf3_3_V_read_int_reg <= src_buf3_3_V_read;
        src_buf3_4_V_read_int_reg <= src_buf3_4_V_read;
        src_buf3_5_V_read_int_reg <= src_buf3_5_V_read;
        src_buf3_6_V_read_int_reg <= src_buf3_6_V_read;
        src_buf4_0_V_read_int_reg <= src_buf4_0_V_read;
        src_buf4_1_V_read_int_reg <= src_buf4_1_V_read;
        src_buf4_2_V_read_int_reg <= src_buf4_2_V_read;
        src_buf4_3_V_read_int_reg <= src_buf4_3_V_read;
        src_buf4_4_V_read_int_reg <= src_buf4_4_V_read;
        src_buf4_5_V_read_int_reg <= src_buf4_5_V_read;
        src_buf4_6_V_read_int_reg <= src_buf4_6_V_read;
        src_buf5_0_V_read_int_reg <= src_buf5_0_V_read;
        src_buf5_1_V_read_int_reg <= src_buf5_1_V_read;
        src_buf5_2_V_read_int_reg <= src_buf5_2_V_read;
        src_buf5_3_V_read_int_reg <= src_buf5_3_V_read;
        src_buf5_4_V_read_int_reg <= src_buf5_4_V_read;
        src_buf5_5_V_read_int_reg <= src_buf5_5_V_read;
        src_buf5_6_V_read_int_reg <= src_buf5_6_V_read;
        src_buf6_0_V_read_int_reg <= src_buf6_0_V_read;
        src_buf6_1_V_read_int_reg <= src_buf6_1_V_read;
        src_buf6_2_V_read_int_reg <= src_buf6_2_V_read;
        src_buf6_3_V_read_int_reg <= src_buf6_3_V_read;
        src_buf6_4_V_read_int_reg <= src_buf6_4_V_read;
        src_buf6_5_V_read_int_reg <= src_buf6_5_V_read;
        src_buf6_6_V_read_int_reg <= src_buf6_6_V_read;
        src_buf7_0_V_read_int_reg <= src_buf7_0_V_read;
        src_buf7_1_V_read_int_reg <= src_buf7_1_V_read;
        src_buf7_2_V_read_int_reg <= src_buf7_2_V_read;
        src_buf7_3_V_read_int_reg <= src_buf7_3_V_read;
        src_buf7_4_V_read_int_reg <= src_buf7_4_V_read;
        src_buf7_5_V_read_int_reg <= src_buf7_5_V_read;
        src_buf7_6_V_read_int_reg <= src_buf7_6_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = value_2_fu_1212_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1218_ce = 1'b1;
    end else begin
        grp_fu_1218_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1228_ce = 1'b1;
    end else begin
        grp_fu_1228_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1234_ce = 1'b1;
    end else begin
        grp_fu_1234_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1240_ce = 1'b1;
    end else begin
        grp_fu_1240_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1246_ce = 1'b1;
    end else begin
        grp_fu_1246_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1255_ce = 1'b1;
    end else begin
        grp_fu_1255_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1264_ce = 1'b1;
    end else begin
        grp_fu_1264_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1273_ce = 1'b1;
    end else begin
        grp_fu_1273_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1279_ce = 1'b1;
    end else begin
        grp_fu_1279_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign grp_fu_1218_p0 = grp_fu_1218_p00;

assign grp_fu_1218_p00 = src_buf4_4_V_read_int_reg;

assign grp_fu_1218_p1 = grp_fu_1218_p10;

assign grp_fu_1218_p10 = src_buf4_2_V_read_int_reg;

assign grp_fu_1218_p2 = 16'd49;

assign grp_fu_1218_p3 = grp_fu_1218_p30;

assign grp_fu_1218_p30 = ret_V_1_reg_1469;

assign grp_fu_1228_p0 = grp_fu_1228_p00;

assign grp_fu_1228_p00 = ret_V_15_reg_1541;

assign grp_fu_1228_p1 = 17'd49;

assign grp_fu_1234_p0 = grp_fu_1234_p00;

assign grp_fu_1234_p00 = ret_V_28_reg_1558;

assign grp_fu_1234_p1 = 17'd49;

assign grp_fu_1240_p0 = grp_fu_1240_p00;

assign grp_fu_1240_p00 = ret_V_41_reg_1575;

assign grp_fu_1240_p1 = 17'd49;

assign grp_fu_1246_p0 = grp_fu_1246_p00;

assign grp_fu_1246_p00 = src_buf7_3_V_read_1_reg_1302_pp0_iter4_reg;

assign grp_fu_1246_p1 = grp_fu_1246_p10;

assign grp_fu_1246_p10 = src_buf1_3_V_read_1_reg_1407_pp0_iter4_reg;

assign grp_fu_1246_p2 = 16'd55;

assign grp_fu_1255_p0 = grp_fu_1255_p00;

assign grp_fu_1255_p00 = src_buf6_3_V_read_1_reg_1337_pp0_iter4_reg;

assign grp_fu_1255_p1 = grp_fu_1255_p10;

assign grp_fu_1255_p10 = src_buf2_3_V_read_1_reg_1402_pp0_iter4_reg;

assign grp_fu_1255_p2 = 16'd55;

assign grp_fu_1264_p0 = grp_fu_1264_p00;

assign grp_fu_1264_p00 = src_buf5_3_V_read_1_reg_1372_pp0_iter4_reg;

assign grp_fu_1264_p1 = grp_fu_1264_p10;

assign grp_fu_1264_p10 = src_buf3_3_V_read_1_reg_1397_pp0_iter4_reg;

assign grp_fu_1264_p2 = 16'd55;

assign grp_fu_1273_p0 = grp_fu_1273_p00;

assign grp_fu_1273_p00 = sum2_reg_1687;

assign grp_fu_1273_p1 = 24'd49;

assign grp_fu_1279_p0 = grp_fu_1279_p00;

assign grp_fu_1279_p00 = tmp1_reg_1697;

assign grp_fu_1279_p2 = 23'd55;

assign lhs_V_10_fu_651_p1 = ret_V_19_reg_1439;

assign lhs_V_11_fu_536_p1 = src_buf2_1_V_read_int_reg;

assign lhs_V_12_fu_663_p1 = ret_V_22_reg_1444;

assign lhs_V_13_fu_550_p1 = src_buf2_2_V_read_int_reg;

assign lhs_V_14_fu_675_p1 = ret_V_26_reg_1449;

assign lhs_V_16_fu_564_p1 = src_buf3_0_V_read_int_reg;

assign lhs_V_17_fu_687_p1 = ret_V_32_reg_1454;

assign lhs_V_18_fu_578_p1 = src_buf3_1_V_read_int_reg;

assign lhs_V_19_fu_699_p1 = ret_V_35_reg_1459;

assign lhs_V_1_fu_458_p1 = src_buf4_1_V_read_int_reg;

assign lhs_V_20_fu_592_p1 = src_buf3_2_V_read_int_reg;

assign lhs_V_21_fu_711_p1 = ret_V_39_reg_1464;

assign lhs_V_2_fu_508_p1 = src_buf1_2_V_read_int_reg;

assign lhs_V_4_fu_639_p1 = ret_V_13_reg_1434;

assign lhs_V_6_fu_480_p1 = src_buf1_0_V_read_int_reg;

assign lhs_V_7_fu_615_p1 = ret_V_3_reg_1424;

assign lhs_V_8_fu_522_p1 = src_buf2_0_V_read_int_reg;

assign lhs_V_9_fu_494_p1 = src_buf1_1_V_read_int_reg;

assign lhs_V_fu_444_p1 = src_buf4_0_V_read_int_reg;

assign lhs_V_s_fu_627_p1 = ret_V_8_reg_1429;

assign p_shl10_cast_fu_907_p1 = p_shl10_fu_900_p3;

assign p_shl10_fu_900_p3 = {{ret_V_24_reg_1552_pp0_iter6_reg}, {1'd0}};

assign p_shl11_cast_fu_988_p1 = p_shl11_fu_981_p3;

assign p_shl11_fu_981_p3 = {{ret_V_21_reg_1546_pp0_iter7_reg}, {4'd0}};

assign p_shl12_cast_fu_999_p1 = p_shl12_fu_992_p3;

assign p_shl12_fu_992_p3 = {{ret_V_21_reg_1546_pp0_iter7_reg}, {1'd0}};

assign p_shl13_cast_fu_868_p1 = p_shl13_fu_861_p3;

assign p_shl13_fu_861_p3 = {{ret_V_11_reg_1535_pp0_iter6_reg}, {5'd0}};

assign p_shl14_cast_fu_879_p1 = p_shl14_fu_872_p3;

assign p_shl14_fu_872_p3 = {{ret_V_11_reg_1535_pp0_iter6_reg}, {1'd0}};

assign p_shl15_cast_fu_952_p1 = p_shl15_fu_945_p3;

assign p_shl15_fu_945_p3 = {{ret_V_7_reg_1529_pp0_iter7_reg}, {4'd0}};

assign p_shl16_cast_fu_963_p1 = p_shl16_fu_956_p3;

assign p_shl16_fu_956_p3 = {{ret_V_7_reg_1529_pp0_iter7_reg}, {1'd0}};

assign p_shl17_cast_fu_730_p1 = p_shl17_fu_723_p3;

assign p_shl17_fu_723_p3 = {{ret_V_5_reg_1418_pp0_iter1_reg}, {5'd0}};

assign p_shl18_cast_fu_741_p1 = p_shl18_fu_734_p3;

assign p_shl18_fu_734_p3 = {{ret_V_5_reg_1418_pp0_iter1_reg}, {1'd0}};

assign p_shl19_cast_fu_1098_p1 = p_shl19_fu_1091_p3;

assign p_shl19_fu_1091_p3 = {{ret_V_2_reg_1412_pp0_iter10_reg}, {1'd0}};

assign p_shl1_cast_fu_1087_p1 = p_shl1_fu_1080_p3;

assign p_shl1_fu_1080_p3 = {{ret_V_2_reg_1412_pp0_iter10_reg}, {4'd0}};

assign p_shl2_cast_fu_1129_p1 = p_shl2_fu_1122_p3;

assign p_shl2_fu_1122_p3 = {{sum1_reg_1681_pp0_iter13_reg}, {1'd0}};

assign p_shl3_cast_fu_1146_p1 = p_shl3_fu_1139_p3;

assign p_shl3_fu_1139_p3 = {{sum_reg_1675_pp0_iter14_reg}, {4'd0}};

assign p_shl4_cast_fu_1118_p1 = p_shl4_fu_1111_p3;

assign p_shl4_fu_1111_p3 = {{sum_reg_1675_pp0_iter13_reg}, {1'd0}};

assign p_shl5_cast_fu_924_p1 = p_shl5_fu_917_p3;

assign p_shl5_fu_917_p3 = {{ret_V_37_reg_1569_pp0_iter6_reg}, {5'd0}};

assign p_shl6_cast_fu_935_p1 = p_shl6_fu_928_p3;

assign p_shl6_fu_928_p3 = {{ret_V_37_reg_1569_pp0_iter6_reg}, {1'd0}};

assign p_shl7_cast_fu_1024_p1 = p_shl7_fu_1017_p3;

assign p_shl7_fu_1017_p3 = {{ret_V_34_reg_1563_pp0_iter7_reg}, {4'd0}};

assign p_shl8_cast_fu_1035_p1 = p_shl8_fu_1028_p3;

assign p_shl8_fu_1028_p3 = {{ret_V_34_reg_1563_pp0_iter7_reg}, {1'd0}};

assign p_shl9_cast_fu_896_p1 = p_shl9_fu_889_p3;

assign p_shl9_fu_889_p3 = {{ret_V_24_reg_1552_pp0_iter6_reg}, {5'd0}};

assign p_shl_cast_fu_1157_p1 = p_shl_fu_1150_p3;

assign p_shl_fu_1150_p3 = {{sum1_reg_1681_pp0_iter14_reg}, {5'd0}};

assign ret_V_10_fu_633_p2 = (rhs_V_7_fu_630_p1 + lhs_V_s_fu_627_p1);

assign ret_V_11_fu_765_p2 = (rhs_V_8_cast_fu_762_p1 + ret_V_10_reg_1479);

assign ret_V_12_fu_883_p2 = (p_shl14_cast_fu_879_p1 + p_shl13_cast_fu_868_p1);

assign ret_V_13_fu_516_p2 = (rhs_V_9_fu_512_p1 + lhs_V_2_fu_508_p1);

assign ret_V_14_fu_645_p2 = (rhs_V_s_fu_642_p1 + lhs_V_4_fu_639_p1);

assign ret_V_15_fu_773_p2 = (rhs_V_10_cast_fu_770_p1 + ret_V_14_reg_1484);

assign ret_V_19_fu_530_p2 = (rhs_V_8_fu_526_p1 + lhs_V_8_fu_522_p1);

assign ret_V_1_fu_609_p0 = ret_V_1_fu_609_p00;

assign ret_V_1_fu_609_p00 = src_buf4_3_V_read_1_reg_1392;

assign ret_V_1_fu_609_p2 = (ret_V_1_fu_609_p0 * $signed('h37));

assign ret_V_20_fu_657_p2 = (rhs_V_10_fu_654_p1 + lhs_V_10_fu_651_p1);

assign ret_V_21_fu_781_p2 = (rhs_V_14_cast_fu_778_p1 + ret_V_20_reg_1489);

assign ret_V_22_fu_544_p2 = (rhs_V_11_fu_540_p1 + lhs_V_11_fu_536_p1);

assign ret_V_23_fu_669_p2 = (rhs_V_12_fu_666_p1 + lhs_V_12_fu_663_p1);

assign ret_V_24_fu_789_p2 = (rhs_V_17_cast_fu_786_p1 + ret_V_23_reg_1494);

assign ret_V_25_fu_911_p2 = (p_shl10_cast_fu_907_p1 + p_shl9_cast_fu_896_p1);

assign ret_V_26_fu_558_p2 = (rhs_V_13_fu_554_p1 + lhs_V_13_fu_550_p1);

assign ret_V_27_fu_681_p2 = (rhs_V_14_fu_678_p1 + lhs_V_14_fu_675_p1);

assign ret_V_28_fu_797_p2 = (rhs_V_20_cast_fu_794_p1 + ret_V_27_reg_1499);

assign ret_V_2_fu_452_p2 = (rhs_V_fu_448_p1 + lhs_V_fu_444_p1);

assign ret_V_32_fu_572_p2 = (rhs_V_16_fu_568_p1 + lhs_V_16_fu_564_p1);

assign ret_V_33_fu_693_p2 = (rhs_V_17_fu_690_p1 + lhs_V_17_fu_687_p1);

assign ret_V_34_fu_805_p2 = (rhs_V_24_cast_fu_802_p1 + ret_V_33_reg_1504);

assign ret_V_35_fu_586_p2 = (rhs_V_18_fu_582_p1 + lhs_V_18_fu_578_p1);

assign ret_V_36_fu_705_p2 = (rhs_V_19_fu_702_p1 + lhs_V_19_fu_699_p1);

assign ret_V_37_fu_813_p2 = (rhs_V_27_cast_fu_810_p1 + ret_V_36_reg_1509);

assign ret_V_38_fu_939_p2 = (p_shl6_cast_fu_935_p1 + p_shl5_cast_fu_924_p1);

assign ret_V_39_fu_600_p2 = (rhs_V_20_fu_596_p1 + lhs_V_20_fu_592_p1);

assign ret_V_3_fu_488_p2 = (rhs_V_3_fu_484_p1 + lhs_V_6_fu_480_p1);

assign ret_V_40_fu_717_p2 = (rhs_V_21_fu_714_p1 + lhs_V_21_fu_711_p1);

assign ret_V_41_fu_821_p2 = (rhs_V_30_cast_fu_818_p1 + ret_V_40_reg_1514);

assign ret_V_4_fu_621_p2 = (rhs_V_4_fu_618_p1 + lhs_V_7_fu_615_p1);

assign ret_V_5_fu_466_p2 = (rhs_V_1_fu_462_p1 + lhs_V_1_fu_458_p1);

assign ret_V_6_fu_745_p2 = (p_shl18_cast_fu_741_p1 + p_shl17_cast_fu_730_p1);

assign ret_V_7_fu_757_p2 = (rhs_V_5_cast_fu_754_p1 + ret_V_4_reg_1474);

assign ret_V_8_fu_502_p2 = (rhs_V_6_fu_498_p1 + lhs_V_9_fu_494_p1);

assign rhs_V_10_cast_fu_770_p1 = src_buf7_4_V_read_1_reg_1297_pp0_iter1_reg;

assign rhs_V_10_fu_654_p1 = src_buf6_0_V_read_1_reg_1352;

assign rhs_V_11_fu_540_p1 = src_buf2_5_V_read_int_reg;

assign rhs_V_12_fu_666_p1 = src_buf6_1_V_read_1_reg_1347;

assign rhs_V_13_fu_554_p1 = src_buf2_4_V_read_int_reg;

assign rhs_V_14_cast_fu_778_p1 = src_buf6_6_V_read_1_reg_1322_pp0_iter1_reg;

assign rhs_V_14_fu_678_p1 = src_buf6_2_V_read_1_reg_1342;

assign rhs_V_16_fu_568_p1 = src_buf3_6_V_read_int_reg;

assign rhs_V_17_cast_fu_786_p1 = src_buf6_5_V_read_1_reg_1327_pp0_iter1_reg;

assign rhs_V_17_fu_690_p1 = src_buf5_0_V_read_1_reg_1387;

assign rhs_V_18_fu_582_p1 = src_buf3_5_V_read_int_reg;

assign rhs_V_19_fu_702_p1 = src_buf5_1_V_read_1_reg_1382;

assign rhs_V_1_fu_462_p1 = src_buf4_5_V_read_int_reg;

assign rhs_V_20_cast_fu_794_p1 = src_buf6_4_V_read_1_reg_1332_pp0_iter1_reg;

assign rhs_V_20_fu_596_p1 = src_buf3_4_V_read_int_reg;

assign rhs_V_21_fu_714_p1 = src_buf5_2_V_read_1_reg_1377;

assign rhs_V_24_cast_fu_802_p1 = src_buf5_6_V_read_1_reg_1357_pp0_iter1_reg;

assign rhs_V_27_cast_fu_810_p1 = src_buf5_5_V_read_1_reg_1362_pp0_iter1_reg;

assign rhs_V_30_cast_fu_818_p1 = src_buf5_4_V_read_1_reg_1367_pp0_iter1_reg;

assign rhs_V_3_fu_484_p1 = src_buf1_6_V_read_int_reg;

assign rhs_V_4_fu_618_p1 = src_buf7_0_V_read_1_reg_1317;

assign rhs_V_5_cast_fu_754_p1 = src_buf7_6_V_read_1_reg_1287_pp0_iter1_reg;

assign rhs_V_6_fu_498_p1 = src_buf1_5_V_read_int_reg;

assign rhs_V_7_fu_630_p1 = src_buf7_1_V_read_1_reg_1312;

assign rhs_V_8_cast_fu_762_p1 = src_buf7_5_V_read_1_reg_1292_pp0_iter1_reg;

assign rhs_V_8_fu_526_p1 = src_buf2_6_V_read_int_reg;

assign rhs_V_9_fu_512_p1 = src_buf1_4_V_read_int_reg;

assign rhs_V_fu_448_p1 = src_buf4_6_V_read_int_reg;

assign rhs_V_s_fu_642_p1 = src_buf7_2_V_read_1_reg_1307;

assign sum1_fu_1064_p2 = (tmp11_cast_fu_1061_p1 + tmp5_reg_1660);

assign sum2_fu_1072_p2 = (tmp14_cast_fu_1069_p1 + tmp11_reg_1670);

assign sum_fu_1056_p2 = (tmp6_cast_fu_1053_p1 + tmp7_reg_1650);

assign tmp11_cast_fu_1061_p1 = tmp_reg_1655;

assign tmp11_fu_1048_p2 = (tmp_18_cast_fu_1039_p1 + tmp10_reg_1640);

assign tmp12_fu_1133_p2 = (p_shl4_cast_fu_1118_p1 + p_shl2_cast_fu_1129_p1);

assign tmp13_fu_1164_p2 = (p_shl_cast_fu_1157_p1 + tmp18_cast_fu_1161_p1);

assign tmp14_cast_fu_1069_p1 = tmp9_reg_1665;

assign tmp15_fu_1170_p2 = (p_shl3_cast_fu_1146_p1 + tmp14_reg_1712);

assign tmp17_cast_fu_1175_p1 = tmp13_reg_1717;

assign tmp18_cast_fu_1161_p1 = tmp12_reg_1707;

assign tmp19_cast_fu_1178_p1 = tmp15_reg_1722;

assign tmp1_fu_1102_p2 = (p_shl19_cast_fu_1098_p1 + p_shl1_cast_fu_1087_p1);

assign tmp2_fu_829_p2 = (tmp_6_cast_fu_826_p1 + tmp3_reg_1524);

assign tmp5_fu_1012_p2 = (tmp_12_cast_fu_1003_p1 + tmp4_reg_1630);

assign tmp6_cast_fu_1053_p1 = tmp6_reg_1645;

assign tmp6_fu_970_p2 = (p_shl15_cast_fu_952_p1 + p_shl16_cast_fu_963_p1);

assign tmp7_fu_976_p2 = (tmp_5_cast_fu_967_p1 + tmp8_reg_1620);

assign tmp9_fu_1042_p2 = (p_shl8_cast_fu_1035_p1 + p_shl7_cast_fu_1024_p1);

assign tmp_12_cast_fu_1003_p1 = ret_V_25_reg_1625;

assign tmp_18_cast_fu_1039_p1 = ret_V_38_reg_1635;

assign tmp_2_fu_1181_p2 = (tmp17_cast_fu_1175_p1 + tmp19_cast_fu_1178_p1);

assign tmp_4_fu_1207_p2 = ((val_cast_reg_1727 > 9'd254) ? 1'b1 : 1'b0);

assign tmp_5_cast_fu_967_p1 = ret_V_12_reg_1615;

assign tmp_6_cast_fu_826_p1 = ret_V_6_reg_1519;

assign tmp_fu_1006_p2 = (p_shl11_cast_fu_988_p1 + p_shl12_cast_fu_999_p1);

assign value_2_fu_1212_p3 = ((tmp_4_reg_1737[0:0] === 1'b1) ? 8'd255 : value_reg_1732_pp0_iter17_reg);

always @ (posedge ap_clk) begin
    ret_V_6_reg_1519[0] <= 1'b0;
    ret_V_12_reg_1615[0] <= 1'b0;
    ret_V_25_reg_1625[0] <= 1'b0;
    ret_V_38_reg_1635[0] <= 1'b0;
    tmp6_reg_1645[0] <= 1'b0;
    tmp_reg_1655[0] <= 1'b0;
    tmp9_reg_1665[0] <= 1'b0;
    tmp1_reg_1697[0] <= 1'b0;
    tmp12_reg_1707[0] <= 1'b0;
    tmp13_reg_1717[0] <= 1'b0;
end

endmodule //xfapplygaussian7x7
