// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module transform_level_0 (
        in_stream_TDATA,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_V_V_TDATA,
        ap_clk,
        ap_rst,
        in_stream_TVALID,
        in_stream_TREADY,
        out_stream_V_V_TVALID,
        out_stream_V_V_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] in_stream_TDATA;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_V_V_TDATA;
input   ap_clk;
input   ap_rst;
input   in_stream_TVALID;
output   in_stream_TREADY;
output   out_stream_V_V_TVALID;
input   out_stream_V_V_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    transform_level_0_Lo_U0_ap_start;
wire    transform_level_0_Lo_U0_ap_done;
wire    transform_level_0_Lo_U0_ap_continue;
wire    transform_level_0_Lo_U0_ap_idle;
wire    transform_level_0_Lo_U0_ap_ready;
wire    transform_level_0_Lo_U0_in_stream_TREADY;
wire   [7:0] transform_level_0_Lo_U0_out_stream_V_V_TDATA;
wire    transform_level_0_Lo_U0_out_stream_V_V_TVALID;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    transform_level_0_Lo_U0_start_full_n;
wire    transform_level_0_Lo_U0_start_write;

transform_level_0_Lo transform_level_0_Lo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(transform_level_0_Lo_U0_ap_start),
    .ap_done(transform_level_0_Lo_U0_ap_done),
    .ap_continue(transform_level_0_Lo_U0_ap_continue),
    .ap_idle(transform_level_0_Lo_U0_ap_idle),
    .ap_ready(transform_level_0_Lo_U0_ap_ready),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TVALID(in_stream_TVALID),
    .in_stream_TREADY(transform_level_0_Lo_U0_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TUSER(in_stream_TUSER),
    .in_stream_TLAST(in_stream_TLAST),
    .in_stream_TID(in_stream_TID),
    .in_stream_TDEST(in_stream_TDEST),
    .out_stream_V_V_TDATA(transform_level_0_Lo_U0_out_stream_V_V_TDATA),
    .out_stream_V_V_TVALID(transform_level_0_Lo_U0_out_stream_V_V_TVALID),
    .out_stream_V_V_TREADY(out_stream_V_V_TREADY)
);

assign ap_done = transform_level_0_Lo_U0_ap_done;

assign ap_idle = transform_level_0_Lo_U0_ap_idle;

assign ap_ready = transform_level_0_Lo_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = transform_level_0_Lo_U0_ap_done;

assign ap_sync_ready = transform_level_0_Lo_U0_ap_ready;

assign in_stream_TREADY = transform_level_0_Lo_U0_in_stream_TREADY;

assign out_stream_V_V_TDATA = transform_level_0_Lo_U0_out_stream_V_V_TDATA;

assign out_stream_V_V_TVALID = transform_level_0_Lo_U0_out_stream_V_V_TVALID;

assign transform_level_0_Lo_U0_ap_continue = ap_continue;

assign transform_level_0_Lo_U0_ap_start = ap_start;

assign transform_level_0_Lo_U0_start_full_n = 1'b1;

assign transform_level_0_Lo_U0_start_write = 1'b0;

endmodule //transform_level_0
