// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFAST (
        src_V_V_TDATA,
        MomentsStreamOut_V_V_TDATA,
        p_image_height,
        p_image_width,
        ap_clk,
        ap_rst,
        src_V_V_TVALID,
        src_V_V_TREADY,
        MomentsStreamOut_V_V_TVALID,
        MomentsStreamOut_V_V_TREADY,
        p_image_height_ap_vld,
        p_image_width_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] src_V_V_TDATA;
output  [87:0] MomentsStreamOut_V_V_TDATA;
input  [10:0] p_image_height;
input  [11:0] p_image_width;
input   ap_clk;
input   ap_rst;
input   src_V_V_TVALID;
output   src_V_V_TREADY;
output   MomentsStreamOut_V_V_TVALID;
input   MomentsStreamOut_V_V_TREADY;
input   p_image_height_ap_vld;
input   p_image_width_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [87:0] xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TDATA;
wire    xFFastCornerDetectio_U0_src_V_V_TREADY;
wire    xFFastCornerDetectio_U0_ap_start;
wire    xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TVALID;
wire    xFFastCornerDetectio_U0_ap_done;
wire    xFFastCornerDetectio_U0_ap_ready;
wire    xFFastCornerDetectio_U0_ap_idle;
wire    xFFastCornerDetectio_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    xFFastCornerDetectio_U0_start_full_n;
wire    xFFastCornerDetectio_U0_start_write;

xFFastCornerDetectio xFFastCornerDetectio_U0(
    .src_V_V_TDATA(src_V_V_TDATA),
    .MomentsStreamOut_V_V_TDATA(xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TDATA),
    .p_image_height(p_image_height),
    .p_image_width(p_image_width),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .src_V_V_TVALID(src_V_V_TVALID),
    .src_V_V_TREADY(xFFastCornerDetectio_U0_src_V_V_TREADY),
    .p_image_height_ap_vld(p_image_height_ap_vld),
    .p_image_width_ap_vld(p_image_width_ap_vld),
    .ap_start(xFFastCornerDetectio_U0_ap_start),
    .MomentsStreamOut_V_V_TVALID(xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TVALID),
    .MomentsStreamOut_V_V_TREADY(MomentsStreamOut_V_V_TREADY),
    .ap_done(xFFastCornerDetectio_U0_ap_done),
    .ap_ready(xFFastCornerDetectio_U0_ap_ready),
    .ap_idle(xFFastCornerDetectio_U0_ap_idle),
    .ap_continue(xFFastCornerDetectio_U0_ap_continue)
);

assign MomentsStreamOut_V_V_TDATA = xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TDATA;

assign MomentsStreamOut_V_V_TVALID = xFFastCornerDetectio_U0_MomentsStreamOut_V_V_TVALID;

assign ap_done = xFFastCornerDetectio_U0_ap_done;

assign ap_idle = xFFastCornerDetectio_U0_ap_idle;

assign ap_ready = xFFastCornerDetectio_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = xFFastCornerDetectio_U0_ap_done;

assign ap_sync_ready = xFFastCornerDetectio_U0_ap_ready;

assign src_V_V_TREADY = xFFastCornerDetectio_U0_src_V_V_TREADY;

assign xFFastCornerDetectio_U0_ap_continue = ap_continue;

assign xFFastCornerDetectio_U0_ap_start = ap_start;

assign xFFastCornerDetectio_U0_start_full_n = 1'b1;

assign xFFastCornerDetectio_U0_start_write = 1'b0;

endmodule //myFAST
