// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module xFFastCornerDetectio (
        src_V_V_TDATA,
        MomentsStreamOut_V_V_TDATA,
        p_image_height,
        p_image_width,
        ap_clk,
        ap_rst,
        src_V_V_TVALID,
        src_V_V_TREADY,
        p_image_height_ap_vld,
        p_image_width_ap_vld,
        ap_start,
        MomentsStreamOut_V_V_TVALID,
        MomentsStreamOut_V_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] src_V_V_TDATA;
output  [87:0] MomentsStreamOut_V_V_TDATA;
input  [10:0] p_image_height;
input  [11:0] p_image_width;
input   ap_clk;
input   ap_rst;
input   src_V_V_TVALID;
output   src_V_V_TREADY;
input   p_image_height_ap_vld;
input   p_image_width_ap_vld;
input   ap_start;
output   MomentsStreamOut_V_V_TVALID;
input   MomentsStreamOut_V_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    xFfast7x777_U0_ap_start;
wire    xFfast7x777_U0_ap_done;
wire    xFfast7x777_U0_ap_continue;
wire    xFfast7x777_U0_ap_idle;
wire    xFfast7x777_U0_ap_ready;
wire    xFfast7x777_U0_start_out;
wire    xFfast7x777_U0_start_write;
wire    xFfast7x777_U0_src_V_V_TREADY;
wire   [15:0] xFfast7x777_U0_datapackStream0_V_V_i_din;
wire    xFfast7x777_U0_datapackStream0_V_V_i_write;
wire   [8:0] xFfast7x777_U0_p_image_height_c_i_din;
wire    xFfast7x777_U0_p_image_height_c_i_write;
wire   [9:0] xFfast7x777_U0_p_image_width_c_i_din;
wire    xFfast7x777_U0_p_image_width_c_i_write;
wire    xFfastnms78_U0_ap_start;
wire    xFfastnms78_U0_ap_done;
wire    xFfastnms78_U0_ap_continue;
wire    xFfastnms78_U0_ap_idle;
wire    xFfastnms78_U0_ap_ready;
wire    xFfastnms78_U0_start_out;
wire    xFfastnms78_U0_start_write;
wire    xFfastnms78_U0_p_src_mat_V_V_read;
wire   [263:0] xFfastnms78_U0_datapackStreamOut_V_V_din;
wire    xFfastnms78_U0_datapackStreamOut_V_V_write;
wire    xFfastnms78_U0_img_height_read;
wire    xFfastnms78_U0_img_width_read;
wire   [8:0] xFfastnms78_U0_img_height_out_din;
wire    xFfastnms78_U0_img_height_out_write;
wire   [9:0] xFfastnms78_U0_img_width_out_din;
wire    xFfastnms78_U0_img_width_out_write;
wire    Moments_U0_ap_start;
wire    Moments_U0_ap_done;
wire    Moments_U0_ap_continue;
wire    Moments_U0_ap_idle;
wire    Moments_U0_ap_ready;
wire    Moments_U0_start_out;
wire    Moments_U0_start_write;
wire    Moments_U0_datapackStreamIn_V_V_read;
wire   [63:0] Moments_U0_momentPackStream_V_V_din;
wire    Moments_U0_momentPackStream_V_V_write;
wire    Moments_U0_img_height_read;
wire    Moments_U0_img_width_read;
wire   [10:0] Moments_U0_img_height_out_din;
wire    Moments_U0_img_height_out_write;
wire   [11:0] Moments_U0_img_width_out_din;
wire    Moments_U0_img_width_out_write;
wire    MCFilter_U0_ap_start;
wire    MCFilter_U0_ap_done;
wire    MCFilter_U0_ap_continue;
wire    MCFilter_U0_ap_idle;
wire    MCFilter_U0_ap_ready;
wire    MCFilter_U0_datapackStreamIn_V_V_read;
wire   [87:0] MCFilter_U0_MomentsStreamOut_V_V_TDATA;
wire    MCFilter_U0_MomentsStreamOut_V_V_TVALID;
wire    MCFilter_U0_img_height_read;
wire    MCFilter_U0_img_width_read;
wire    ap_sync_continue;
wire    datapackStream0_V_V_full_n;
wire   [15:0] datapackStream0_V_V_dout;
wire    datapackStream0_V_V_empty_n;
wire    p_image_height_c_i_full_n;
wire   [8:0] p_image_height_c_i_dout;
wire    p_image_height_c_i_empty_n;
wire    p_image_width_c_i_full_n;
wire   [9:0] p_image_width_c_i_dout;
wire    p_image_width_c_i_empty_n;
wire    datapackStream1_V_V_full_n;
wire   [263:0] datapackStream1_V_V_dout;
wire    datapackStream1_V_V_empty_n;
wire    p_image_height_c3_i_full_n;
wire   [8:0] p_image_height_c3_i_dout;
wire    p_image_height_c3_i_empty_n;
wire    p_image_width_c4_i_full_n;
wire   [9:0] p_image_width_c4_i_dout;
wire    p_image_width_c4_i_empty_n;
wire    datapackStream2_V_V_full_n;
wire   [63:0] datapackStream2_V_V_dout;
wire    datapackStream2_V_V_empty_n;
wire    p_image_height_c5_i_full_n;
wire   [10:0] p_image_height_c5_i_dout;
wire    p_image_height_c5_i_empty_n;
wire    p_image_width_c6_i_full_n;
wire   [11:0] p_image_width_c6_i_dout;
wire    p_image_width_c6_i_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_xFfastnms78_U0_din;
wire    start_for_xFfastnms78_U0_full_n;
wire   [0:0] start_for_xFfastnms78_U0_dout;
wire    start_for_xFfastnms78_U0_empty_n;
wire   [0:0] start_for_Moments_U0_din;
wire    start_for_Moments_U0_full_n;
wire   [0:0] start_for_Moments_U0_dout;
wire    start_for_Moments_U0_empty_n;
wire   [0:0] start_for_MCFilter_U0_din;
wire    start_for_MCFilter_U0_full_n;
wire   [0:0] start_for_MCFilter_U0_dout;
wire    start_for_MCFilter_U0_empty_n;
wire    MCFilter_U0_start_full_n;
wire    MCFilter_U0_start_write;

xFfast7x777 xFfast7x777_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFfast7x777_U0_ap_start),
    .start_full_n(start_for_xFfastnms78_U0_full_n),
    .ap_done(xFfast7x777_U0_ap_done),
    .ap_continue(xFfast7x777_U0_ap_continue),
    .ap_idle(xFfast7x777_U0_ap_idle),
    .ap_ready(xFfast7x777_U0_ap_ready),
    .start_out(xFfast7x777_U0_start_out),
    .start_write(xFfast7x777_U0_start_write),
    .src_V_V_TDATA(src_V_V_TDATA),
    .src_V_V_TVALID(src_V_V_TVALID),
    .src_V_V_TREADY(xFfast7x777_U0_src_V_V_TREADY),
    .datapackStream0_V_V_i_din(xFfast7x777_U0_datapackStream0_V_V_i_din),
    .datapackStream0_V_V_i_full_n(datapackStream0_V_V_full_n),
    .datapackStream0_V_V_i_write(xFfast7x777_U0_datapackStream0_V_V_i_write),
    .p_image_height(p_image_height),
    .p_image_width(p_image_width),
    .p_image_height_c_i_din(xFfast7x777_U0_p_image_height_c_i_din),
    .p_image_height_c_i_full_n(p_image_height_c_i_full_n),
    .p_image_height_c_i_write(xFfast7x777_U0_p_image_height_c_i_write),
    .p_image_width_c_i_din(xFfast7x777_U0_p_image_width_c_i_din),
    .p_image_width_c_i_full_n(p_image_width_c_i_full_n),
    .p_image_width_c_i_write(xFfast7x777_U0_p_image_width_c_i_write)
);

xFfastnms78 xFfastnms78_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFfastnms78_U0_ap_start),
    .start_full_n(start_for_Moments_U0_full_n),
    .ap_done(xFfastnms78_U0_ap_done),
    .ap_continue(xFfastnms78_U0_ap_continue),
    .ap_idle(xFfastnms78_U0_ap_idle),
    .ap_ready(xFfastnms78_U0_ap_ready),
    .start_out(xFfastnms78_U0_start_out),
    .start_write(xFfastnms78_U0_start_write),
    .p_src_mat_V_V_dout(datapackStream0_V_V_dout),
    .p_src_mat_V_V_empty_n(datapackStream0_V_V_empty_n),
    .p_src_mat_V_V_read(xFfastnms78_U0_p_src_mat_V_V_read),
    .datapackStreamOut_V_V_din(xFfastnms78_U0_datapackStreamOut_V_V_din),
    .datapackStreamOut_V_V_full_n(datapackStream1_V_V_full_n),
    .datapackStreamOut_V_V_write(xFfastnms78_U0_datapackStreamOut_V_V_write),
    .img_height_dout(p_image_height_c_i_dout),
    .img_height_empty_n(p_image_height_c_i_empty_n),
    .img_height_read(xFfastnms78_U0_img_height_read),
    .img_width_dout(p_image_width_c_i_dout),
    .img_width_empty_n(p_image_width_c_i_empty_n),
    .img_width_read(xFfastnms78_U0_img_width_read),
    .img_height_out_din(xFfastnms78_U0_img_height_out_din),
    .img_height_out_full_n(p_image_height_c3_i_full_n),
    .img_height_out_write(xFfastnms78_U0_img_height_out_write),
    .img_width_out_din(xFfastnms78_U0_img_width_out_din),
    .img_width_out_full_n(p_image_width_c4_i_full_n),
    .img_width_out_write(xFfastnms78_U0_img_width_out_write)
);

Moments Moments_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Moments_U0_ap_start),
    .start_full_n(start_for_MCFilter_U0_full_n),
    .ap_done(Moments_U0_ap_done),
    .ap_continue(Moments_U0_ap_continue),
    .ap_idle(Moments_U0_ap_idle),
    .ap_ready(Moments_U0_ap_ready),
    .start_out(Moments_U0_start_out),
    .start_write(Moments_U0_start_write),
    .datapackStreamIn_V_V_dout(datapackStream1_V_V_dout),
    .datapackStreamIn_V_V_empty_n(datapackStream1_V_V_empty_n),
    .datapackStreamIn_V_V_read(Moments_U0_datapackStreamIn_V_V_read),
    .momentPackStream_V_V_din(Moments_U0_momentPackStream_V_V_din),
    .momentPackStream_V_V_full_n(datapackStream2_V_V_full_n),
    .momentPackStream_V_V_write(Moments_U0_momentPackStream_V_V_write),
    .img_height_dout(p_image_height_c3_i_dout),
    .img_height_empty_n(p_image_height_c3_i_empty_n),
    .img_height_read(Moments_U0_img_height_read),
    .img_width_dout(p_image_width_c4_i_dout),
    .img_width_empty_n(p_image_width_c4_i_empty_n),
    .img_width_read(Moments_U0_img_width_read),
    .img_height_out_din(Moments_U0_img_height_out_din),
    .img_height_out_full_n(p_image_height_c5_i_full_n),
    .img_height_out_write(Moments_U0_img_height_out_write),
    .img_width_out_din(Moments_U0_img_width_out_din),
    .img_width_out_full_n(p_image_width_c6_i_full_n),
    .img_width_out_write(Moments_U0_img_width_out_write)
);

MCFilter MCFilter_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MCFilter_U0_ap_start),
    .ap_done(MCFilter_U0_ap_done),
    .ap_continue(MCFilter_U0_ap_continue),
    .ap_idle(MCFilter_U0_ap_idle),
    .ap_ready(MCFilter_U0_ap_ready),
    .datapackStreamIn_V_V_dout(datapackStream2_V_V_dout),
    .datapackStreamIn_V_V_empty_n(datapackStream2_V_V_empty_n),
    .datapackStreamIn_V_V_read(MCFilter_U0_datapackStreamIn_V_V_read),
    .MomentsStreamOut_V_V_TDATA(MCFilter_U0_MomentsStreamOut_V_V_TDATA),
    .MomentsStreamOut_V_V_TVALID(MCFilter_U0_MomentsStreamOut_V_V_TVALID),
    .MomentsStreamOut_V_V_TREADY(MomentsStreamOut_V_V_TREADY),
    .img_height_dout(p_image_height_c5_i_dout),
    .img_height_empty_n(p_image_height_c5_i_empty_n),
    .img_height_read(MCFilter_U0_img_height_read),
    .img_width_dout(p_image_width_c6_i_dout),
    .img_width_empty_n(p_image_width_c6_i_empty_n),
    .img_width_read(MCFilter_U0_img_width_read)
);

fifo_w16_d2_A datapackStream0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfast7x777_U0_datapackStream0_V_V_i_din),
    .if_full_n(datapackStream0_V_V_full_n),
    .if_write(xFfast7x777_U0_datapackStream0_V_V_i_write),
    .if_dout(datapackStream0_V_V_dout),
    .if_empty_n(datapackStream0_V_V_empty_n),
    .if_read(xFfastnms78_U0_p_src_mat_V_V_read)
);

fifo_w9_d2_A p_image_height_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfast7x777_U0_p_image_height_c_i_din),
    .if_full_n(p_image_height_c_i_full_n),
    .if_write(xFfast7x777_U0_p_image_height_c_i_write),
    .if_dout(p_image_height_c_i_dout),
    .if_empty_n(p_image_height_c_i_empty_n),
    .if_read(xFfastnms78_U0_img_height_read)
);

fifo_w10_d2_A p_image_width_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfast7x777_U0_p_image_width_c_i_din),
    .if_full_n(p_image_width_c_i_full_n),
    .if_write(xFfast7x777_U0_p_image_width_c_i_write),
    .if_dout(p_image_width_c_i_dout),
    .if_empty_n(p_image_width_c_i_empty_n),
    .if_read(xFfastnms78_U0_img_width_read)
);

fifo_w264_d2_A datapackStream1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfastnms78_U0_datapackStreamOut_V_V_din),
    .if_full_n(datapackStream1_V_V_full_n),
    .if_write(xFfastnms78_U0_datapackStreamOut_V_V_write),
    .if_dout(datapackStream1_V_V_dout),
    .if_empty_n(datapackStream1_V_V_empty_n),
    .if_read(Moments_U0_datapackStreamIn_V_V_read)
);

fifo_w9_d2_A p_image_height_c3_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfastnms78_U0_img_height_out_din),
    .if_full_n(p_image_height_c3_i_full_n),
    .if_write(xFfastnms78_U0_img_height_out_write),
    .if_dout(p_image_height_c3_i_dout),
    .if_empty_n(p_image_height_c3_i_empty_n),
    .if_read(Moments_U0_img_height_read)
);

fifo_w10_d2_A p_image_width_c4_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFfastnms78_U0_img_width_out_din),
    .if_full_n(p_image_width_c4_i_full_n),
    .if_write(xFfastnms78_U0_img_width_out_write),
    .if_dout(p_image_width_c4_i_dout),
    .if_empty_n(p_image_width_c4_i_empty_n),
    .if_read(Moments_U0_img_width_read)
);

fifo_w64_d2_A datapackStream2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Moments_U0_momentPackStream_V_V_din),
    .if_full_n(datapackStream2_V_V_full_n),
    .if_write(Moments_U0_momentPackStream_V_V_write),
    .if_dout(datapackStream2_V_V_dout),
    .if_empty_n(datapackStream2_V_V_empty_n),
    .if_read(MCFilter_U0_datapackStreamIn_V_V_read)
);

fifo_w11_d2_A p_image_height_c5_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Moments_U0_img_height_out_din),
    .if_full_n(p_image_height_c5_i_full_n),
    .if_write(Moments_U0_img_height_out_write),
    .if_dout(p_image_height_c5_i_dout),
    .if_empty_n(p_image_height_c5_i_empty_n),
    .if_read(MCFilter_U0_img_height_read)
);

fifo_w12_d2_A p_image_width_c6_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Moments_U0_img_width_out_din),
    .if_full_n(p_image_width_c6_i_full_n),
    .if_write(Moments_U0_img_width_out_write),
    .if_dout(p_image_width_c6_i_dout),
    .if_empty_n(p_image_width_c6_i_empty_n),
    .if_read(MCFilter_U0_img_width_read)
);

start_for_xFfastnEe0 start_for_xFfastnEe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFfastnms78_U0_din),
    .if_full_n(start_for_xFfastnms78_U0_full_n),
    .if_write(xFfast7x777_U0_start_write),
    .if_dout(start_for_xFfastnms78_U0_dout),
    .if_empty_n(start_for_xFfastnms78_U0_empty_n),
    .if_read(xFfastnms78_U0_ap_ready)
);

start_for_MomentsFfa start_for_MomentsFfa_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Moments_U0_din),
    .if_full_n(start_for_Moments_U0_full_n),
    .if_write(xFfastnms78_U0_start_write),
    .if_dout(start_for_Moments_U0_dout),
    .if_empty_n(start_for_Moments_U0_empty_n),
    .if_read(Moments_U0_ap_ready)
);

start_for_MCFilteGfk start_for_MCFilteGfk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MCFilter_U0_din),
    .if_full_n(start_for_MCFilter_U0_full_n),
    .if_write(Moments_U0_start_write),
    .if_dout(start_for_MCFilter_U0_dout),
    .if_empty_n(start_for_MCFilter_U0_empty_n),
    .if_read(MCFilter_U0_ap_ready)
);

assign MCFilter_U0_ap_continue = ap_continue;

assign MCFilter_U0_ap_start = start_for_MCFilter_U0_empty_n;

assign MCFilter_U0_start_full_n = 1'b1;

assign MCFilter_U0_start_write = 1'b0;

assign MomentsStreamOut_V_V_TDATA = MCFilter_U0_MomentsStreamOut_V_V_TDATA;

assign MomentsStreamOut_V_V_TVALID = MCFilter_U0_MomentsStreamOut_V_V_TVALID;

assign Moments_U0_ap_continue = 1'b1;

assign Moments_U0_ap_start = start_for_Moments_U0_empty_n;

assign ap_done = MCFilter_U0_ap_done;

assign ap_idle = (xFfastnms78_U0_ap_idle & xFfast7x777_U0_ap_idle & Moments_U0_ap_idle & MCFilter_U0_ap_idle);

assign ap_ready = xFfast7x777_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = MCFilter_U0_ap_done;

assign ap_sync_ready = xFfast7x777_U0_ap_ready;

assign src_V_V_TREADY = xFfast7x777_U0_src_V_V_TREADY;

assign start_for_MCFilter_U0_din = 1'b1;

assign start_for_Moments_U0_din = 1'b1;

assign start_for_xFfastnms78_U0_din = 1'b1;

assign xFfast7x777_U0_ap_continue = 1'b1;

assign xFfast7x777_U0_ap_start = ap_start;

assign xFfastnms78_U0_ap_continue = 1'b1;

assign xFfastnms78_U0_ap_start = start_for_xFfastnms78_U0_empty_n;

endmodule //xFFastCornerDetectio
